using System;

namespace ChartForgeX.Tests;

internal static partial class SmokeTests {
    internal static (string Name, Action Run)[] Tests { get; } = {
        ("Source files stay under architecture line budget", SourceFilesStayUnderArchitectureLineBudget),
        ("Project files keep strict build settings", ProjectFilesKeepStrictBuildSettings),
        ("Example app clears generated output before writing", ExampleAppClearsGeneratedOutputBeforeWriting),
        ("SVG markup writer streams escaped elements", SvgMarkupWriterStreamsEscapedElements),
        ("HTML markup writer streams escaped elements", HtmlMarkupWriterStreamsEscapedElements),
        ("SVG AST builds editable ordered markup", SvgAstBuildsEditableOrderedMarkup),
        ("SVG AST supports query and attribute editing", SvgAstSupportsQueryAndAttributeEditing),
        ("SVG AST supports structural editing and cloning", SvgAstSupportsStructuralEditingAndCloning),
        ("SVG AST parses edits and saves SVG markup", SvgAstParsesEditsAndSavesSvgMarkup),
        ("SVG AST rejects unsafe DTD content", SvgAstRejectsUnsafeDtdContent),
        ("SVG AST rejects multiple parents", SvgAstRejectsMultipleParents),
        ("SVG markup writer rejects incomplete markup", SvgMarkupWriterRejectsIncompleteMarkup),
        ("HTML markup writer rejects incomplete markup", HtmlMarkupWriterRejectsIncompleteMarkup),
        ("SVG path data builder formats deterministic paths", SvgPathDataBuilderFormatsDeterministicPaths),
        ("SVG path data parses and normalizes commands", SvgPathDataParsesAndNormalizesCommands),
        ("SVG path data edits loaded path elements", SvgPathDataEditsLoadedPathElements),
        ("SVG path data rejects malformed commands", SvgPathDataRejectsMalformedCommands),
        ("SVG transform list parses and normalizes transforms", SvgTransformListParsesAndNormalizesTransforms),
        ("SVG transform list edits loaded elements", SvgTransformListEditsLoadedElements),
        ("SVG transform list rejects malformed transforms", SvgTransformListRejectsMalformedTransforms),
        ("SVG style declaration list parses and normalizes styles", SvgStyleDeclarationListParsesAndNormalizesStyles),
        ("SVG style declaration list edits loaded elements", SvgStyleDeclarationListEditsLoadedElements),
        ("SVG style declaration list rejects malformed styles", SvgStyleDeclarationListRejectsMalformedStyles),
        ("SVG viewBox parses edits and saves root viewport", SvgViewBoxParsesEditsAndSavesRootViewport),
        ("SVG viewBox rejects malformed values", SvgViewBoxRejectsMalformedValues),
        ("SVG point list parses edits and saves polygon points", SvgPointListParsesEditsAndSavesPolygonPoints),
        ("SVG point list rejects malformed values", SvgPointListRejectsMalformedValues),
        ("SVG markup engine stays dependency-free and streaming", SvgMarkupEngineStaysDependencyFreeAndStreaming),
        ("HTML markup engine stays dependency-free and adopted", HtmlMarkupEngineStaysDependencyFreeAndAdopted),
        ("Europe revenue map routes target rendered markers", EuropeRevenueMapRoutesTargetRenderedMarkers),
        ("Build script verifies release artifacts", BuildScriptVerifiesReleaseArtifacts),
        ("NuGet package metadata stays publish-ready", NuGetPackageMetadataStaysPublishReady),
        ("README documents chart catalog", ReadmeDocumentsChartCatalog),
        ("Visual baseline is structured and actionable", VisualBaselineIsStructuredAndActionable),
        ("GitHub Actions use self-hosted runners", GitHubActionsUsePrivateRunners),
        ("SVG escapes text and renders inline vectors", SvgEscapesText),
        ("HTML page is static and JavaScript-free", HtmlPageIsStatic),
        ("Rendered markup stays self-contained", RenderedMarkupStaysSelfContained),
        ("PNG renderer emits a valid RGBA PNG", PngIsValid),
        ("PNG output is deflate-compressed", PngOutputIsCompressed),
        ("SVG and PNG preserve requested dimensions across chart kinds", SvgAndPngPreserveRequestedDimensionsAcrossChartKinds),
        ("PNG renderer uses readable axis layout", PngUsesReadableAxisLayout),
        ("PNG renderer uses supersampled edges", PngUsesSupersampledEdges),
        ("PNG supersampling scale is configurable", PngSupersamplingScaleIsConfigurable),
        ("PNG output scale emits high-density assets", PngOutputScaleEmitsHighDensityAssets),
        ("PNG print scale survives dense chart stress", PngPrintScaleSurvivesDenseChartStress),
        ("Overlay preset emits transparent chrome-free PNG", OverlayPresetEmitsTransparentChromeFreePng),
        ("PNG smooth series use curved raster paths", PngSmoothSeriesUseCurvedRasterPaths),
        ("PNG renderer renders report chrome", PngRendersReportChrome),
        ("PNG outline fonts use em-sized text", PngOutlineFontsUseEmSizedText),
        ("PNG renderer uses emphasized report text", PngRendererUsesEmphasizedReportText),
        ("PNG chart renderer uses theme-sized text", PngChartRendererUsesThemeSizedText),
        ("PNG and SVG stroke primitives stay aligned", PngAndSvgStrokePrimitivesStayAligned),
        ("PNG font path falls back gracefully", PngFontPathFallsBackGracefully),
        ("PNG font path supports TrueType collections", PngFontPathSupportsTrueTypeCollections),
        ("PNG font diagnostics describe fallback decisions", PngFontDiagnosticsDescribeFallbackDecisions),
        ("PNG TrueType renderer handles composite glyphs", PngTrueTypeRendererHandlesCompositeGlyphs),
        ("PNG TrueType renderer supports kerning", PngTrueTypeRendererSupportsKerning),
        ("PNG surfaces use rounded corners", PngSurfacesUseRoundedCorners),
        ("PNG annotations use readable raster styling", PngAnnotationsUseReadableRasterStyling),
        ("PNG pie-like charts use readable details", PngPieLikeChartsUseReadableDetails),
        ("PNG data labels use readable halos", PngDataLabelsUseReadableHalos),
        ("PNG readable labels fit inside plot bounds", PngReadableLabelsFitInsidePlotBounds),
        ("PNG heatmaps render cell value labels", PngHeatmapsRenderCellValueLabels),
        ("PNG timelines render readable raster details", PngTimelinesRenderReadableRasterDetails),
        ("Area baseline does not pollute the x-axis", AreaBaselineDoesNotPolluteXAxis),
        ("X-axis labels render in SVG", XAxisLabelsRender),
        ("Axis visibility can be configured independently", AxisVisibilityCanBeConfiguredIndependently),
        ("Smooth series render as Bezier paths", SmoothSeriesRenderAsBezierPaths),
        ("PNG scatter does not connect points", PngScatterDoesNotConnectPoints),
        ("Step line series render as stair steps", StepLineSeriesRenderAsStairSteps),
        ("Step area series render as stair-step areas", StepAreaSeriesRenderAsStairStepAreas),
        ("Data labels render when enabled", DataLabelsRenderWhenEnabled),
        ("Point callouts use custom point labels", PointCalloutsUseCustomPointLabels),
        ("Series data label overrides are honored", SeriesDataLabelOverridesAreHonored),
        ("Series fluent styling controls color stroke and smoothing", SeriesFluentStylingControlsColorStrokeAndSmoothing),
        ("Series fill patterns render for filled marks", SeriesFillPatternsRenderForFilledMarks),
        ("Series data-label styles override chart defaults", SeriesDataLabelStylesOverrideChartDefaults),
        ("Specialized series data-label styles override chart defaults", SpecializedSeriesDataLabelStylesOverrideChartDefaults),
        ("Point data-label styles override series defaults", PointDataLabelStylesOverrideSeriesDefaults),
        ("Point colors override series color for bars", PointColorsOverrideSeriesColorForBars),
        ("Map point colors override series color", MapPointColorsOverrideSeriesColor),
        ("Zero-value specialized charts preserve point indexes", ZeroValueSpecializedChartsPreservePointIndexes),
        ("Data-label placement can be configured", DataLabelPlacementCanBeConfigured),
        ("Specialized data-label placement can be configured", SpecializedDataLabelPlacementCanBeConfigured),
        ("Series fluent styling rejects invalid stroke widths", SeriesFluentStylingRejectsInvalidStrokeWidths),
        ("Timeline and Gantt series data label overrides are honored", TimelineAndGanttSeriesDataLabelOverridesAreHonored),
        ("Specialized series data label overrides are honored", SpecializedSeriesDataLabelOverridesAreHonored),
        ("Intrinsic specialized labels can be suppressed", IntrinsicSpecializedLabelsCanBeSuppressed),
        ("Hierarchy labels can be suppressed", HierarchyLabelsCanBeSuppressed),
        ("Bullet labels can be suppressed", BulletLabelsCanBeSuppressed),
        ("Horizontal series data label overrides reserve layout", HorizontalSeriesDataLabelOverridesReserveLayout),
        ("Point label overrides reach specialized data labels", PointLabelOverridesReachSpecializedDataLabels),
        ("Dense point labels avoid collisions", DensePointLabelsAvoidCollisions),
        ("Dense bar labels avoid collisions", DenseBarLabelsAvoidCollisions),
        ("Dense comparison labels avoid collisions", DenseComparisonLabelsAvoidCollisions),
        ("Dense financial and total labels avoid collisions", DenseFinancialAndTotalLabelsAvoidCollisions),
        ("Data labels use readable edge-aware SVG styling", DataLabelsUseReadableEdgeAwareStyling),
        ("Custom value formatter affects SVG values", CustomValueFormatterAffectsSvgValues),
        ("Custom x-axis formatter affects SVG and PNG ticks", CustomXAxisFormatterAffectsSvgAndPngTicks),
        ("Long formatted y-axis labels reserve plot space", LongFormattedYAxisLabelsReservePlotSpace),
        ("Long axis titles fit available space", LongAxisTitlesFitAvailableSpace),
        ("Long header text fits available space", LongHeaderTextFitsAvailableSpace),
        ("Annotations render in SVG", AnnotationsRenderInSvg),
        ("Statistical overlays render computed annotations", StatisticalOverlaysRenderComputedAnnotations),
        ("Annotation labels stay inside the plot", AnnotationLabelsStayInsidePlot),
        ("Legends and data labels keep guard gaps", LegendsAndDataLabelsKeepGuardGaps),
        ("SVG includes accessibility metadata", SvgIncludesAccessibilityMetadata),
        ("SVG uses report-grade visual styling", SvgUsesReportGradeStyling),
        ("SVG interactive regions support static hover and focus", SvgInteractiveRegionsSupportStaticHoverAndFocus),
        ("Interactivity contracts are host neutral", InteractivityContractsAreHostNeutral),
        ("Interactive HTML wraps SVG without external dependencies", InteractiveHtmlWrapsSvgWithoutExternalDependencies),
        ("Interactive HTML escapes host provided attributes", InteractiveHtmlEscapesHostProvidedAttributes),
        ("Interactive HTML dashboard synchronizes multiple charts", InteractiveHtmlDashboardSynchronizesMultipleCharts),
        ("Typography uses a native font stack and escapes custom families", TypographyUsesNativeFontStackAndEscapesCustomFamilies),
        ("Brand kits apply reusable tokens", BrandKitsApplyReusableTokens),
        ("Rendering uses invariant culture", RenderingUsesInvariantCulture),
        ("Report themes expose visual quality tokens", ReportThemesExposeVisualTokens),
        ("Standalone HTML uses a visible page background", StandaloneHtmlUsesVisibleBackground),
        ("HTML fragment is responsive and self-contained", HtmlFragmentIsResponsive),
        ("Small multiple grids render static HTML", SmallMultipleGridRendersStaticHtml),
        ("Shared y-axis handles secondary-only charts", SharedYAxisHandlesSecondaryOnlyCharts),
        ("Shared axes ignore progress bars", SharedAxesIgnoreProgressBars),
        ("Chart grids support panel spans", ChartGridsSupportPanelSpans),
        ("Chart grid headers support text styles", ChartGridHeadersSupportTextStyles),
        ("Visual blocks render tables lists and metric cards", VisualBlocksRenderTablesListsAndMetricCards),
        ("Visual grid composes charts and visual blocks", VisualGridComposesChartsAndVisualBlocks),
        ("Visual blocks reject invalid inputs close to caller", VisualBlocksRejectInvalidInputsCloseToCaller),
        ("Explicit axis bounds affect SVG ticks", ExplicitAxisBoundsAffectSvgTicks),
        ("Example gallery is static and links generated artifacts", ExampleGalleryIsStaticAndLinksGeneratedArtifacts),
        ("Example gallery baseline flags high-density regressions", ExampleGalleryBaselineFlagsHighDensityRegressions),
        ("Dense x-axis labels are automatically reduced", DenseXAxisLabelsAreAutomaticallyReduced),
        ("Formatted numeric x-axis ticks thin when crowded", FormattedNumericXAxisTicksThinWhenCrowded),
        ("Horizontal category labels wrap in SVG", HorizontalCategoryLabelsWrapInSvg),
        ("Edge x-axis labels stay inside the plot", EdgeXAxisLabelsStayInsidePlot),
        ("X-axis labels can be rotated", XAxisLabelsCanBeRotated),
        ("Large SVG values use compact units", LargeSvgValuesUseCompactUnits),
        ("Default numeric compact formatter is shared", DefaultNumericCompactFormatterIsShared),
        ("Legend rows wrap without leaving the layout implicit", LegendRowsWrapWithRoleMarkers),
        ("Histogram values render as binned bars", HistogramValuesRenderAsBinnedBars),
        ("Lollipop series render stems and markers", LollipopSeriesRenderStemsAndMarkers),
        ("Range bar series render intervals", RangeBarSeriesRenderIntervals),
        ("Box plot series render statistical summaries", BoxPlotSeriesRenderStatisticalSummaries),
        ("Bubble series render scaled markers", BubbleSeriesRenderScaledMarkers),
        ("Secondary-axis bubble range ignores bubble sizes", SecondaryAxisBubbleRangeIgnoresBubbleSizes),
        ("Trend-line series render computed regression lines", TrendLineSeriesRenderComputedRegressionLines),
        ("Error-bar series render bounds and markers", ErrorBarSeriesRenderBoundsAndMarkers),
        ("Candlestick series render OHLC bodies and wicks", CandlestickSeriesRenderOhlcBodiesAndWicks),
        ("OHLC series render open and close ticks", OhlcSeriesRenderOpenAndCloseTicks),
        ("Range-band series render filled envelopes", RangeBandSeriesRenderFilledEnvelopes),
        ("Range-area series render filled interval areas", RangeAreaSeriesRenderFilledIntervalAreas),
        ("Stacked-area series render cumulative filled bands", StackedAreaSeriesRenderCumulativeFilledBands),
        ("Slope series render endpoint comparisons", SlopeSeriesRenderEndpointComparisons),
        ("Dumbbell series render paired comparisons", DumbbellSeriesRenderPairedComparisons),
        ("Pareto items render sorted bars and cumulative line", ParetoItemsRenderSortedBarsAndCumulativeLine),
        ("Bar-line combo renders bars and line", BarLineComboRendersBarsAndLine),
        ("Combo helpers render mixed series", ComboHelpersRenderMixedSeries),
        ("Multiple bar series render as grouped bars", MultipleBarSeriesRenderAsGroupedBars),
        ("Horizontal bar series render category bars", HorizontalBarSeriesRenderCategoryBars),
        ("Stacked horizontal bars render segments and totals", StackedHorizontalBarsRenderSegmentsAndTotals),
        ("Heatmap rows render matrix cells", HeatmapRowsRenderMatrixCells),
        ("Heatmap rows accept matrix values", HeatmapRowsAcceptMatrixValues),
        ("Heatmap rows can mask cells", HeatmapRowsCanMaskCells),
        ("Hexbin heatmap rows render honeycomb cells", HexbinHeatmapRowsRenderHoneycombCells),
        ("Hexbin heatmap rows accept one-based values", HexbinHeatmapRowsAcceptOneBasedValues),
        ("Hexbin heatmap rows accept matrix values", HexbinHeatmapRowsAcceptMatrixValues),
        ("Hexbin heatmap rows can mask honeycomb cells", HexbinHeatmapRowsCanMaskHoneycombCells),
        ("Calendar heatmap renders contribution grid", CalendarHeatmapRendersContributionGrid),
        ("Calendar heatmap does not label padding months", CalendarHeatmapDoesNotLabelPaddingMonths),
        ("Calendar heatmap complete weeks do not show no-data scale", CalendarHeatmapCompleteWeeksDoNotShowNoDataScale),
        ("Calendar heatmap uses local contribution range", CalendarHeatmapUsesLocalContributionRange),
        ("Dotted map renders world dots and points", DottedMapRendersWorldDotsAndPoints),
        ("Topology renders demo SVG", TopologyRendersDemoSvg),
        ("Topology SVG renderer uses SVG markup engine", TopologySvgRendererUsesSvgMarkupEngine),
        ("Topology default legend is product neutral", TopologyDefaultLegendIsProductNeutral),
        ("Topology legend grows for domain specific items", TopologyLegendGrowsForDomainSpecificItems),
        ("Topology normalizes overlapping manual content", TopologyNormalizesOverlappingManualContent),
        ("Topology fits manual content into viewport", TopologyFitsManualContentIntoViewport),
        ("Topology reserves group header space", TopologyReservesGroupHeaderSpace),
        ("Topology renders deterministic layouts", TopologyRendersDeterministicLayouts),
        ("Topology layered layouts can flow left to right", TopologyLayeredLayoutsCanFlowLeftToRight),
        ("Topology dense grouped layout packs groups and nodes", TopologyDenseGroupedLayoutPacksGroupsAndNodes),
        ("Topology dense grouped layout supports group policies", TopologyDenseGroupedLayoutSupportsGroupPolicies),
        ("Topology dense grouped layout assigns inter-group edge defaults", TopologyDenseGroupedLayoutAssignsInterGroupEdgeDefaults),
        ("Topology geographic layout projects coordinates", TopologyGeographicLayoutProjectsCoordinates),
        ("Topology escapes text and skips unsafe href", TopologyEscapesTextAndSkipsUnsafeHref),
        ("Topology emits safe CSS and data hooks", TopologyEmitsSafeCssAndDataHooks),
        ("Topology HTML pages expose selection interactions", TopologyHtmlPagesExposeSelectionInteractions),
        ("Topology validator reports actionable errors", TopologyValidatorReportsActionableErrors),
        ("Topology validator rejects invalid dimensions", TopologyValidatorRejectsInvalidDimensions),
        ("Topology fluent APIs reject invalid inputs", TopologyFluentApisRejectInvalidInputs),
        ("Topology views render focused subsets", TopologyViewsRenderFocusedSubsets),
        ("Topology views filter by kind status and neighbors", TopologyViewsFilterByKindStatusAndNeighbors),
        ("Topology edge labels avoid nodes", TopologyEdgeLabelsAvoidNodes),
        ("Topology edge labels avoid unrelated edges", TopologyEdgeLabelsAvoidUnrelatedEdges),
        ("Topology parallel edges route with deterministic offsets", TopologyParallelEdgesRouteWithDeterministicOffsets),
        ("Topology edges support manual waypoints", TopologyEdgesSupportManualWaypoints),
        ("Topology edges support ports and route lanes", TopologyEdgesSupportPortsAndRouteLanes),
        ("Topology edges can avoid node obstacles", TopologyEdgesCanAvoidNodeObstacles),
        ("Topology edges can avoid group headers", TopologyEdgesCanAvoidGroupHeaders),
        ("Topology render options support dashboard perspectives", TopologyRenderOptionsSupportDashboardPerspectives),
        ("Topology presets and node display modes render dense views", TopologyPresetsAndNodeDisplayModesRenderDenseViews),
        ("Topology nodes can override display mode and badges", TopologyNodesCanOverrideDisplayModeAndBadges),
        ("Topology inferred legends are generic and data driven", TopologyInferredLegendsAreGenericAndDataDriven),
        ("Dotted map trims point labels", DottedMapTrimsPointLabels),
        ("Dotted map world viewport suppresses polar points outside map band", DottedMapWorldViewportSuppressesPolarPointsOutsideMapBand),
        ("Dotted map data labels suppress polar points outside map band", DottedMapDataLabelsSuppressPolarPointsOutsideMapBand),
        ("Dotted map clustered labels use alternate placements", DottedMapClusteredLabelsUseAlternatePlacements),
        ("Dotted map dense clusters use diagonal label placements", DottedMapDenseClustersUseDiagonalLabelPlacements),
        ("Dotted map preserves map aspect ratio in tall cards", DottedMapPreservesMapAspectRatioInTallCards),
        ("Dotted map viewport focuses regional maps", DottedMapViewportFocusesRegionalMaps),
        ("Dotted map regional labels avoid marker halos", DottedMapRegionalLabelsAvoidMarkerHalos),
        ("Dotted map renders weighted revenue markers", DottedMapRendersWeightedRevenueMarkers),
        ("Dotted map renders connector routes", DottedMapRendersConnectorRoutes),
        ("Region map renders reusable map definition", RegionMapRendersReusableMapDefinition),
        ("Tile map renders reusable tile-map definition", TileMapRendersReusableTileMapDefinition),
        ("Map catalogs expose built-in definitions by ID", MapCatalogsExposeBuiltInDefinitionsById),
        ("Map catalogs and definitions expose immutable lists", MapCatalogsAndDefinitionsExposeImmutableLists),
        ("Map definitions accept region names and aliases", MapDefinitionsAcceptRegionNamesAndAliases),
        ("Custom map definitions preserve region identifier casing", CustomMapDefinitionsPreserveRegionIdentifierCasing),
        ("Custom map definitions validate geometry inputs", CustomMapDefinitionsValidateGeometryInputs),
        ("Custom region maps parse standard SVG path separators", CustomRegionMapsParseStandardSvgPathSeparators),
        ("Custom region map PNG preserves interior holes", CustomRegionMapPngPreservesInteriorHoles),
        ("Custom region maps parse common SVG path commands", CustomRegionMapsParseCommonSvgPathCommands),
        ("Custom region maps preserve subunit bounds aspect ratio", CustomRegionMapsPreserveSubunitBoundsAspectRatio),
        ("Tile map labels can be hidden for compact cards", TileMapLabelsCanBeHiddenForCompactCards),
        ("Region map scale legend can be hidden for compact cards", RegionMapScaleLegendCanBeHiddenForCompactCards),
        ("Region map labels only render when regions have room", RegionMapLabelsOnlyRenderWhenRegionsHaveRoom),
        ("Tile map scale legend can be hidden for compact cards", TileMapScaleLegendCanBeHiddenForCompactCards),
        ("Map scale legend separates no data from low values", MapScaleLegendSeparatesNoDataFromLowValues),
        ("Map no-data scale stays inside compact cards", MapNoDataScaleStaysInsideCompactCards),
        ("Heatmap honors axes visibility", HeatmapHonorsAxesVisibility),
        ("Gauge series render value arcs", GaugeSeriesRenderValueArcs),
        ("Circle series render single progress rings", CircleSeriesRenderSingleProgressRings),
        ("Radial bar series render progress rings", RadialBarSeriesRenderProgressRings),
        ("Layered radial series render independent arc layers", LayeredRadialSeriesRenderIndependentArcLayers),
        ("Donut and radial center labels are optional", DonutAndRadialCenterLabelsAreOptional),
        ("Text style overrides render across roles", TextStyleOverridesRenderAcrossRoles),
        ("Gantt tasks render progress dependencies and milestones", GanttTasksRenderProgressDependenciesAndMilestones),
        ("Sankey links render weighted flows", SankeyLinksRenderWeightedFlows),
        ("Tree links render hierarchy", TreeLinksRenderHierarchy),
        ("Sunburst links render radial hierarchy", SunburstLinksRenderRadialHierarchy),
        ("Hierarchy and flow SVG expose data metadata", HierarchyAndFlowSvgExposeDataMetadata),
        ("Bullet series render target and range bars", BulletSeriesRenderTargetAndRangeBars),
        ("Specialized charts escape text labels", SpecializedChartsEscapeTextLabels),
        ("Pie and donut SVG expose slice metadata", PieAndDonutSvgExposeSliceMetadata),
        ("Specialized SVG segments expose data metadata", SpecializedSvgSegmentsExposeDataMetadata),
        ("Comparison and interval SVG expose data metadata", ComparisonAndIntervalSvgExposeDataMetadata),
        ("Cartesian SVG elements expose point metadata", CartesianSvgElementsExposePointMetadata),
        ("Overlay SVG elements expose data metadata", OverlaySvgElementsExposeDataMetadata),
        ("Waterfall series render cumulative change bars", WaterfallSeriesRenderCumulativeChangeBars),
        ("Waterfall honors axes visibility", WaterfallHonorsAxesVisibility),
        ("Radar series render polar polygons", RadarSeriesRenderPolarPolygons),
        ("Radar honors axes and grid visibility", RadarHonorsAxesAndGridVisibility),
        ("Polar-area series render radial segments", PolarAreaSeriesRenderRadialSegments),
        ("Polar-area honors grid visibility", PolarAreaHonorsGridVisibility),
        ("Funnel series render staged segments", FunnelSeriesRenderStagedSegments),
        ("Treemap items render proportional tiles", TreemapItemsRenderProportionalTiles),
        ("Pictorial items render symbol rows", PictorialItemsRenderSymbolRows),
        ("Progress bars render slider rows", ProgressBarsRenderSliderRows),
        ("Word cloud terms render weighted layout", WordCloudTermsRenderWeightedLayout),
        ("Specialized charts fit long SVG labels", SpecializedChartsFitLongSvgLabels),
        ("Timeline items render date ranges", TimelineItemsRenderDateRanges),
        ("Timeline and Gantt honor explicit x-axis bounds", TimelineAndGanttHonorExplicitXAxisBounds),
        ("Multiple bar series can render as stacked bars", MultipleBarSeriesCanRenderAsStackedBars),
        ("Stacked bars can render total labels", StackedBarsCanRenderTotalLabels),
        ("SVG output has no invalid numeric values", SvgHasNoInvalidNumbers),
        ("Date x-axis labels render in SVG", DateXAxisLabelsRender),
        ("Sparkline hides report chrome", SparklineHidesReportChrome),
        ("Public API rejects invalid inputs", PublicApiRejectsInvalidInputs),
        ("Specialized charts reject mixed series", SpecializedChartsRejectMixedSeries),
        ("Donut chart renders slices and labels", DonutChartRendersSlices),
        ("Single-slice donut renders full ring", SingleSliceDonutRendersFullRing)
    };
}
