using System;

namespace ChartForgeX.Tests;

internal static partial class SmokeTests {
    internal static (string Name, Action Run)[] Tests { get; } = {
        ("Source files stay under architecture line budget", SourceFilesStayUnderArchitectureLineBudget),
        ("Project files keep strict build settings", ProjectFilesKeepStrictBuildSettings),
        ("Example app clears generated output before writing", ExampleAppClearsGeneratedOutputBeforeWriting),
        ("Build script verifies release artifacts", BuildScriptVerifiesReleaseArtifacts),
        ("NuGet package metadata stays publish-ready", NuGetPackageMetadataStaysPublishReady),
        ("README documents chart catalog", ReadmeDocumentsChartCatalog),
        ("Visual baseline is structured and actionable", VisualBaselineIsStructuredAndActionable),
        ("GitHub Actions use private runners", GitHubActionsUsePrivateRunners),
        ("SVG escapes text and renders inline vectors", SvgEscapesText),
        ("HTML page is static and JavaScript-free", HtmlPageIsStatic),
        ("Rendered markup stays self-contained", RenderedMarkupStaysSelfContained),
        ("PNG renderer emits a valid RGBA PNG", PngIsValid),
        ("PNG output is deflate-compressed", PngOutputIsCompressed),
        ("SVG and PNG preserve requested dimensions across chart kinds", SvgAndPngPreserveRequestedDimensionsAcrossChartKinds),
        ("PNG renderer uses readable axis layout", PngUsesReadableAxisLayout),
        ("PNG renderer uses supersampled edges", PngUsesSupersampledEdges),
        ("PNG supersampling scale is configurable", PngSupersamplingScaleIsConfigurable),
        ("PNG output scale emits high-density assets", PngOutputScaleEmitsHighDensityAssets),
        ("PNG print scale survives dense chart stress", PngPrintScaleSurvivesDenseChartStress),
        ("PNG smooth series use curved raster paths", PngSmoothSeriesUseCurvedRasterPaths),
        ("PNG renderer renders report chrome", PngRendersReportChrome),
        ("PNG outline fonts use em-sized text", PngOutlineFontsUseEmSizedText),
        ("PNG renderer uses emphasized report text", PngRendererUsesEmphasizedReportText),
        ("PNG chart renderer uses theme-sized text", PngChartRendererUsesThemeSizedText),
        ("PNG and SVG stroke primitives stay aligned", PngAndSvgStrokePrimitivesStayAligned),
        ("PNG font path falls back gracefully", PngFontPathFallsBackGracefully),
        ("PNG font path supports TrueType collections", PngFontPathSupportsTrueTypeCollections),
        ("PNG font diagnostics describe fallback decisions", PngFontDiagnosticsDescribeFallbackDecisions),
        ("PNG TrueType renderer handles composite glyphs", PngTrueTypeRendererHandlesCompositeGlyphs),
        ("PNG TrueType renderer supports kerning", PngTrueTypeRendererSupportsKerning),
        ("PNG surfaces use rounded corners", PngSurfacesUseRoundedCorners),
        ("PNG annotations use readable raster styling", PngAnnotationsUseReadableRasterStyling),
        ("PNG pie-like charts use readable details", PngPieLikeChartsUseReadableDetails),
        ("PNG data labels use readable halos", PngDataLabelsUseReadableHalos),
        ("PNG readable labels fit inside plot bounds", PngReadableLabelsFitInsidePlotBounds),
        ("PNG heatmaps render cell value labels", PngHeatmapsRenderCellValueLabels),
        ("PNG timelines render readable raster details", PngTimelinesRenderReadableRasterDetails),
        ("Area baseline does not pollute the x-axis", AreaBaselineDoesNotPolluteXAxis),
        ("X-axis labels render in SVG", XAxisLabelsRender),
        ("Axis visibility can be configured independently", AxisVisibilityCanBeConfiguredIndependently),
        ("Smooth series render as Bezier paths", SmoothSeriesRenderAsBezierPaths),
        ("PNG scatter does not connect points", PngScatterDoesNotConnectPoints),
        ("Step line series render as stair steps", StepLineSeriesRenderAsStairSteps),
        ("Step area series render as stair-step areas", StepAreaSeriesRenderAsStairStepAreas),
        ("Data labels render when enabled", DataLabelsRenderWhenEnabled),
        ("Series data label overrides are honored", SeriesDataLabelOverridesAreHonored),
        ("Series fluent styling controls color stroke and smoothing", SeriesFluentStylingControlsColorStrokeAndSmoothing),
        ("Series data-label styles override chart defaults", SeriesDataLabelStylesOverrideChartDefaults),
        ("Specialized series data-label styles override chart defaults", SpecializedSeriesDataLabelStylesOverrideChartDefaults),
        ("Point data-label styles override series defaults", PointDataLabelStylesOverrideSeriesDefaults),
        ("Point colors override series color for bars", PointColorsOverrideSeriesColorForBars),
        ("Zero-value specialized charts preserve point indexes", ZeroValueSpecializedChartsPreservePointIndexes),
        ("Data-label placement can be configured", DataLabelPlacementCanBeConfigured),
        ("Specialized data-label placement can be configured", SpecializedDataLabelPlacementCanBeConfigured),
        ("Series fluent styling rejects invalid stroke widths", SeriesFluentStylingRejectsInvalidStrokeWidths),
        ("Timeline and Gantt series data label overrides are honored", TimelineAndGanttSeriesDataLabelOverridesAreHonored),
        ("Specialized series data label overrides are honored", SpecializedSeriesDataLabelOverridesAreHonored),
        ("Intrinsic specialized labels can be suppressed", IntrinsicSpecializedLabelsCanBeSuppressed),
        ("Hierarchy labels can be suppressed", HierarchyLabelsCanBeSuppressed),
        ("Bullet labels can be suppressed", BulletLabelsCanBeSuppressed),
        ("Horizontal series data label overrides reserve layout", HorizontalSeriesDataLabelOverridesReserveLayout),
        ("Dense point labels avoid collisions", DensePointLabelsAvoidCollisions),
        ("Dense bar labels avoid collisions", DenseBarLabelsAvoidCollisions),
        ("Dense comparison labels avoid collisions", DenseComparisonLabelsAvoidCollisions),
        ("Dense financial and total labels avoid collisions", DenseFinancialAndTotalLabelsAvoidCollisions),
        ("Data labels use readable edge-aware SVG styling", DataLabelsUseReadableEdgeAwareStyling),
        ("Custom value formatter affects SVG values", CustomValueFormatterAffectsSvgValues),
        ("Custom x-axis formatter affects SVG and PNG ticks", CustomXAxisFormatterAffectsSvgAndPngTicks),
        ("Long formatted y-axis labels reserve plot space", LongFormattedYAxisLabelsReservePlotSpace),
        ("Long axis titles fit available space", LongAxisTitlesFitAvailableSpace),
        ("Long header text fits available space", LongHeaderTextFitsAvailableSpace),
        ("Annotations render in SVG", AnnotationsRenderInSvg),
        ("Statistical overlays render computed annotations", StatisticalOverlaysRenderComputedAnnotations),
        ("Annotation labels stay inside the plot", AnnotationLabelsStayInsidePlot),
        ("Legends and data labels keep guard gaps", LegendsAndDataLabelsKeepGuardGaps),
        ("SVG includes accessibility metadata", SvgIncludesAccessibilityMetadata),
        ("SVG uses report-grade visual styling", SvgUsesReportGradeStyling),
        ("Typography uses a native font stack and escapes custom families", TypographyUsesNativeFontStackAndEscapesCustomFamilies),
        ("Brand kits apply reusable tokens", BrandKitsApplyReusableTokens),
        ("Rendering uses invariant culture", RenderingUsesInvariantCulture),
        ("Report themes expose visual quality tokens", ReportThemesExposeVisualTokens),
        ("Standalone HTML uses a visible page background", StandaloneHtmlUsesVisibleBackground),
        ("HTML fragment is responsive and self-contained", HtmlFragmentIsResponsive),
        ("Small multiple grids render static HTML", SmallMultipleGridRendersStaticHtml),
        ("Shared y-axis handles secondary-only charts", SharedYAxisHandlesSecondaryOnlyCharts),
        ("Chart grids support panel spans", ChartGridsSupportPanelSpans),
        ("Chart grid headers support text styles", ChartGridHeadersSupportTextStyles),
        ("Explicit axis bounds affect SVG ticks", ExplicitAxisBoundsAffectSvgTicks),
        ("Example gallery is static and links generated artifacts", ExampleGalleryIsStaticAndLinksGeneratedArtifacts),
        ("Example gallery baseline flags high-density regressions", ExampleGalleryBaselineFlagsHighDensityRegressions),
        ("Dense x-axis labels are automatically reduced", DenseXAxisLabelsAreAutomaticallyReduced),
        ("Formatted numeric x-axis ticks thin when crowded", FormattedNumericXAxisTicksThinWhenCrowded),
        ("Horizontal category labels wrap in SVG", HorizontalCategoryLabelsWrapInSvg),
        ("Edge x-axis labels stay inside the plot", EdgeXAxisLabelsStayInsidePlot),
        ("X-axis labels can be rotated", XAxisLabelsCanBeRotated),
        ("Large SVG values use compact units", LargeSvgValuesUseCompactUnits),
        ("Default numeric compact formatter is shared", DefaultNumericCompactFormatterIsShared),
        ("Legend rows wrap without leaving the layout implicit", LegendRowsWrapWithRoleMarkers),
        ("Histogram values render as binned bars", HistogramValuesRenderAsBinnedBars),
        ("Lollipop series render stems and markers", LollipopSeriesRenderStemsAndMarkers),
        ("Range bar series render intervals", RangeBarSeriesRenderIntervals),
        ("Box plot series render statistical summaries", BoxPlotSeriesRenderStatisticalSummaries),
        ("Bubble series render scaled markers", BubbleSeriesRenderScaledMarkers),
        ("Trend-line series render computed regression lines", TrendLineSeriesRenderComputedRegressionLines),
        ("Error-bar series render bounds and markers", ErrorBarSeriesRenderBoundsAndMarkers),
        ("Candlestick series render OHLC bodies and wicks", CandlestickSeriesRenderOhlcBodiesAndWicks),
        ("OHLC series render open and close ticks", OhlcSeriesRenderOpenAndCloseTicks),
        ("Range-band series render filled envelopes", RangeBandSeriesRenderFilledEnvelopes),
        ("Range-area series render filled interval areas", RangeAreaSeriesRenderFilledIntervalAreas),
        ("Stacked-area series render cumulative filled bands", StackedAreaSeriesRenderCumulativeFilledBands),
        ("Slope series render endpoint comparisons", SlopeSeriesRenderEndpointComparisons),
        ("Dumbbell series render paired comparisons", DumbbellSeriesRenderPairedComparisons),
        ("Pareto items render sorted bars and cumulative line", ParetoItemsRenderSortedBarsAndCumulativeLine),
        ("Bar-line combo renders bars and line", BarLineComboRendersBarsAndLine),
        ("Combo helpers render mixed series", ComboHelpersRenderMixedSeries),
        ("Multiple bar series render as grouped bars", MultipleBarSeriesRenderAsGroupedBars),
        ("Horizontal bar series render category bars", HorizontalBarSeriesRenderCategoryBars),
        ("Stacked horizontal bars render segments and totals", StackedHorizontalBarsRenderSegmentsAndTotals),
        ("Heatmap rows render matrix cells", HeatmapRowsRenderMatrixCells),
        ("Heatmap honors axes visibility", HeatmapHonorsAxesVisibility),
        ("Gauge series render value arcs", GaugeSeriesRenderValueArcs),
        ("Circle series render single progress rings", CircleSeriesRenderSingleProgressRings),
        ("Radial bar series render progress rings", RadialBarSeriesRenderProgressRings),
        ("Donut and radial center labels are optional", DonutAndRadialCenterLabelsAreOptional),
        ("Text style overrides render across roles", TextStyleOverridesRenderAcrossRoles),
        ("Gantt tasks render progress dependencies and milestones", GanttTasksRenderProgressDependenciesAndMilestones),
        ("Sankey links render weighted flows", SankeyLinksRenderWeightedFlows),
        ("Tree links render hierarchy", TreeLinksRenderHierarchy),
        ("Sunburst links render radial hierarchy", SunburstLinksRenderRadialHierarchy),
        ("Hierarchy and flow SVG expose data metadata", HierarchyAndFlowSvgExposeDataMetadata),
        ("Bullet series render target and range bars", BulletSeriesRenderTargetAndRangeBars),
        ("Specialized charts escape text labels", SpecializedChartsEscapeTextLabels),
        ("Pie and donut SVG expose slice metadata", PieAndDonutSvgExposeSliceMetadata),
        ("Specialized SVG segments expose data metadata", SpecializedSvgSegmentsExposeDataMetadata),
        ("Comparison and interval SVG expose data metadata", ComparisonAndIntervalSvgExposeDataMetadata),
        ("Cartesian SVG elements expose point metadata", CartesianSvgElementsExposePointMetadata),
        ("Overlay SVG elements expose data metadata", OverlaySvgElementsExposeDataMetadata),
        ("Waterfall series render cumulative change bars", WaterfallSeriesRenderCumulativeChangeBars),
        ("Waterfall honors axes visibility", WaterfallHonorsAxesVisibility),
        ("Radar series render polar polygons", RadarSeriesRenderPolarPolygons),
        ("Radar honors axes and grid visibility", RadarHonorsAxesAndGridVisibility),
        ("Polar-area series render radial segments", PolarAreaSeriesRenderRadialSegments),
        ("Polar-area honors grid visibility", PolarAreaHonorsGridVisibility),
        ("Funnel series render staged segments", FunnelSeriesRenderStagedSegments),
        ("Treemap items render proportional tiles", TreemapItemsRenderProportionalTiles),
        ("Pictorial items render symbol rows", PictorialItemsRenderSymbolRows),
        ("Progress bars render slider rows", ProgressBarsRenderSliderRows),
        ("Word cloud terms render weighted layout", WordCloudTermsRenderWeightedLayout),
        ("Specialized charts fit long SVG labels", SpecializedChartsFitLongSvgLabels),
        ("Timeline items render date ranges", TimelineItemsRenderDateRanges),
        ("Timeline and Gantt honor explicit x-axis bounds", TimelineAndGanttHonorExplicitXAxisBounds),
        ("Multiple bar series can render as stacked bars", MultipleBarSeriesCanRenderAsStackedBars),
        ("Stacked bars can render total labels", StackedBarsCanRenderTotalLabels),
        ("SVG output has no invalid numeric values", SvgHasNoInvalidNumbers),
        ("Date x-axis labels render in SVG", DateXAxisLabelsRender),
        ("Sparkline hides report chrome", SparklineHidesReportChrome),
        ("Public API rejects invalid inputs", PublicApiRejectsInvalidInputs),
        ("Specialized charts reject mixed series", SpecializedChartsRejectMixedSeries),
        ("Donut chart renders slices and labels", DonutChartRendersSlices),
        ("Single-slice donut renders full ring", SingleSliceDonutRendersFullRing)
    };
}
