/// <summary>
/// Writes the static example gallery page.
/// </summary>
public static partial class GalleryWriter {
    private const string IndexFileName = "index.html";
    private const string CatalogFileName = "catalog.html";
    private const string QualityDashboardFileName = "quality-dashboard.html";
    private const string ComparisonFileName = "svg-png-comparison.html";
    private const string ComparisonManifestFileName = "svg-png-comparison.json";
    private const string VisualBaselineFileName = "visual-baseline.json";
    private const int MinimumHealthySvgVisualNodes = 2;
    private const double MinimumReadableSvgTextFontSize = 8;
    private const double MinimumReadableSvgStrokeWidth = 0.75;
    private const double MinimumReadableSvgMarkerRadius = 3;
    private const long MinimumHealthyPngVisiblePixels = 64;
    private const int MinimumHealthyPngDistinctColors = 8;
    private const long MaximumHealthyPngEdgeInkPixels = 0;
    private const double SvgTextCanvasMargin = 1;

    /// <summary>
    /// Generates an index page for all chart HTML files in the output directory.
    /// </summary>
    /// <param name="output">The directory containing generated chart files.</param>
    public static void Write(string output) {
        ExampleCodeSamples.Write(output);
        var htmlFiles = Directory.EnumerateFiles(output, "*.html", SearchOption.TopDirectoryOnly)
            .Where(file => !IsGalleryShellFile(Path.GetFileName(file)))
            .Where(file => !IsConflictCopyFile(file))
            .OrderBy(file => Path.GetFileName(file), StringComparer.OrdinalIgnoreCase)
            .ToArray();
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("<!doctype html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.AppendLine("<title>ChartForgeX Examples</title>");
        sb.AppendLine("<style>");
        sb.AppendLine(":root{color-scheme:dark;--bg:#0f172a;--panel:#111827;--panel2:#0b1120;--preview:#0c1220;--line:#253247;--softline:#1f2b3f;--text:#f8fafc;--muted:#aab6ca;--accent:#38bdf8}");
        sb.AppendLine("*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,Segoe UI,Arial,sans-serif;-webkit-font-smoothing:antialiased}");
        sb.AppendLine("header{padding:36px 40px 18px}h1{margin:0 0 8px;font-size:30px;line-height:1.1}p{margin:0;color:var(--muted);font-size:14px}nav{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}");
        sb.AppendLine("main{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,540px),1fr));gap:22px;padding:22px 40px 44px;align-items:start}.card{min-width:0;border:1px solid var(--line);border-radius:8px;background:linear-gradient(180deg,var(--panel),var(--panel2));overflow:hidden;box-shadow:0 14px 30px rgba(0,0,0,.18)}");
        sb.AppendLine(".preview{display:grid;place-items:center;aspect-ratio:var(--preview-aspect,16/10);background:var(--preview);border-bottom:1px solid var(--softline);padding:12px}.preview img{display:block;max-width:100%;max-height:100%;object-fit:contain}.preview iframe{display:block;width:100%;height:100%;border:0;background:var(--preview)}.body{padding:14px 16px 16px}.title{font-weight:780;font-size:15px;line-height:1.24;margin-bottom:10px}");
        sb.AppendLine(".links{display:flex;flex-wrap:wrap;gap:8px}a{color:var(--accent);text-decoration:none;font-size:12px;font-weight:700;border:1px solid rgba(56,189,248,.28);border-radius:6px;padding:6px 8px}a:hover{background:rgba(56,189,248,.12)}");
        sb.AppendLine("@media(max-width:680px){header{padding:26px 18px 12px}main{grid-template-columns:1fr;padding:18px}.preview{aspect-ratio:4/3;padding:12px}}");
        sb.AppendLine("</style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");
        sb.AppendLine("<header>");
        sb.AppendLine("<h1>ChartForgeX Examples</h1>");
        sb.AppendLine("<p>Static zero-dependency SVG, HTML, and PNG chart outputs generated by the example project.</p>");
        sb.AppendLine("<nav><a href=\"" + CatalogFileName + "\">Grouped catalog</a><a href=\"" + QualityDashboardFileName + "\">Quality dashboard</a><a href=\"" + ComparisonFileName + "\">SVG/PNG comparison</a></nav>");
        sb.AppendLine("</header>");
        sb.AppendLine("<main>");

        foreach (var htmlFile in htmlFiles) {
            AppendCard(sb, htmlFile);
        }

        sb.AppendLine("</main>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
        File.WriteAllText(Path.Combine(output, IndexFileName), sb.ToString());
        WriteCatalog(output, htmlFiles);
        WriteComparison(output);
    }

    private static void AppendCard(System.Text.StringBuilder sb, string htmlFile) {
        var fileName = Path.GetFileName(htmlFile);
        var baseName = Path.GetFileNameWithoutExtension(htmlFile);
        var directory = Path.GetDirectoryName(htmlFile) ?? string.Empty;
        var svgExists = File.Exists(Path.Combine(directory, baseName + ".svg"));
        var pngExists = File.Exists(Path.Combine(directory, baseName + ".png"));
        var csharpExists = File.Exists(Path.Combine(directory, baseName + ".csharp.txt"));
        var title = ReadTitle(htmlFile);
        sb.AppendLine("<article class=\"card\">");
        if (svgExists) {
            var previewStyle = CatalogPreviewStyle(Path.Combine(directory, baseName + ".svg"));
            sb.AppendLine("<a class=\"preview\" href=\"" + EscapeHtml(fileName) + "\" aria-label=\"Open " + EscapeHtml(title) + "\"" + previewStyle + "><img loading=\"lazy\" src=\"" + EscapeHtml(baseName) + ".svg\" alt=\"\"></a>");
        } else {
            sb.AppendLine("<div class=\"preview\"><iframe loading=\"lazy\" src=\"" + EscapeHtml(fileName) + "\" title=\"" + EscapeHtml(title) + "\"></iframe></div>");
        }
        sb.AppendLine("<div class=\"body\">");
        sb.AppendLine("<div class=\"title\">" + EscapeHtml(title) + "</div>");
        sb.AppendLine("<div class=\"links\">");
        sb.AppendLine("<a href=\"" + EscapeHtml(fileName) + "\">HTML</a>");
        if (svgExists) sb.AppendLine("<a href=\"" + EscapeHtml(baseName) + ".svg\">SVG</a>");
        if (pngExists) sb.AppendLine("<a href=\"" + EscapeHtml(baseName) + ".png\">PNG</a>");
        if (csharpExists) sb.AppendLine("<a href=\"" + EscapeHtml(baseName) + ".csharp.txt\">C#</a>");
        sb.AppendLine("</div>");
        sb.AppendLine("</div>");
        sb.AppendLine("</article>");
    }

    private static string ReadTitle(string htmlFile) {
        var html = File.ReadAllText(htmlFile);
        var start = html.IndexOf("<title>", StringComparison.OrdinalIgnoreCase);
        var end = html.IndexOf("</title>", StringComparison.OrdinalIgnoreCase);
        if (start < 0 || end <= start) return Path.GetFileNameWithoutExtension(htmlFile);
        return html.Substring(start + 7, end - start - 7).Trim();
    }

    private static void WriteComparison(string output) {
        var pairs = Directory.EnumerateFiles(output, "*.svg", SearchOption.TopDirectoryOnly)
            .Where(file => !IsConflictCopyFile(file))
            .Select(Path.GetFileNameWithoutExtension)
            .Where(name => !string.IsNullOrWhiteSpace(name) && File.Exists(Path.Combine(output, name + ".png")))
            .Select(name => name!)
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
            .Select(name => ReadComparisonAsset(output, name))
            .ToArray();
        var matchingPairs = pairs.Count(pair => pair.HasMatchingDimensions);
        var healthySvgs = pairs.Count(pair => pair.SvgHealth.IsHealthy);
        var healthyPngs = pairs.Count(pair => pair.PngHealth.IsHealthy);
        var healthyHtmls = pairs.Count(pair => pair.HtmlHealth.IsHealthy);
        var warningCount = pairs.Sum(pair => pair.Warnings.Length);
        var baseline = ReadBaselineSummary(output, pairs);
        var groups = BuildComparisonGroups(pairs);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("<!doctype html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.AppendLine("<title>ChartForgeX SVG/PNG visual comparison</title>");
        sb.AppendLine("<style>");
        AppendComparisonStyle(sb);
        sb.AppendLine("</style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");
        sb.AppendLine("<header>");
        sb.AppendLine("<h1>ChartForgeX SVG/PNG visual comparison</h1>");
        sb.AppendLine("<p>Generated from current example exports. SVG is left, PNG is right; high-density PNGs are shown at their logical SVG size.</p>");
        sb.AppendLine("<div class=\"summary\"><span class=\"pill\">" + pairs.Length.ToString(System.Globalization.CultureInfo.InvariantCulture) + " chart pairs</span><span class=\"pill " + (matchingPairs == pairs.Length ? "ok" : "warn") + "\">" + matchingPairs.ToString(System.Globalization.CultureInfo.InvariantCulture) + " dimension matches</span><span class=\"pill " + (healthySvgs == pairs.Length ? "ok" : "warn") + "\">" + healthySvgs.ToString(System.Globalization.CultureInfo.InvariantCulture) + " healthy SVGs</span><span class=\"pill " + (healthyPngs == pairs.Length ? "ok" : "warn") + "\">" + healthyPngs.ToString(System.Globalization.CultureInfo.InvariantCulture) + " healthy PNGs</span><span class=\"pill " + (healthyHtmls == pairs.Length ? "ok" : "warn") + "\">" + healthyHtmls.ToString(System.Globalization.CultureInfo.InvariantCulture) + " healthy HTMLs</span><span class=\"pill " + (warningCount == 0 ? "ok" : "warn") + "\">" + warningCount.ToString(System.Globalization.CultureInfo.InvariantCulture) + " warnings</span>" + FormatBaselinePill(baseline) + "<a class=\"pill\" href=\"" + CatalogFileName + "\">grouped catalog</a><a class=\"pill\" href=\"" + QualityDashboardFileName + "\">quality dashboard</a><a class=\"pill\" href=\"" + ComparisonManifestFileName + "\">manifest JSON</a></div>");
        AppendComparisonFamilyNav(sb, groups);
        sb.AppendLine("</header>");
        sb.AppendLine("<main>");

        foreach (var group in groups) {
            AppendComparisonGroup(sb, group, output);
        }

        sb.AppendLine("</main>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
        File.WriteAllText(Path.Combine(output, ComparisonFileName), sb.ToString());
        WriteQualityDashboard(output, pairs, matchingPairs, baseline);
        WriteComparisonManifest(output, pairs, matchingPairs, baseline);
    }

    private static ComparisonGroup[] BuildComparisonGroups(ComparisonAsset[] pairs) {
        var assigned = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var groups = new List<ComparisonGroup>();
        foreach (var catalogGroup in CatalogGroups) {
            var groupPairs = pairs.Where(pair => catalogGroup.Contains(pair.Name)).ToArray();
            if (groupPairs.Length == 0) continue;
            foreach (var pair in groupPairs) assigned.Add(pair.Name);
            groups.Add(new ComparisonGroup(catalogGroup.Name, catalogGroup.Description, groupPairs));
        }

        var remaining = pairs.Where(pair => !assigned.Contains(pair.Name)).ToArray();
        if (remaining.Length > 0) {
            groups.Add(new ComparisonGroup(
                "Additional Visual Checks",
                "Generated SVG/PNG pairs not yet assigned to a named catalog family.",
                remaining));
        }

        return groups.ToArray();
    }

    private static void AppendComparisonFamilyNav(System.Text.StringBuilder sb, ComparisonGroup[] groups) {
        if (groups.Length == 0) return;
        sb.AppendLine("<div class=\"family-nav\" aria-label=\"Comparison families\">");
        foreach (var group in groups) {
            sb.AppendLine("<a class=\"" + (group.IsClean ? "ok" : "warn") + "\" href=\"#comparison-family-" + EscapeHtml(Slugify(group.Name)) + "\">" + EscapeHtml(group.Name) + " (" + group.CleanPairs.ToString(System.Globalization.CultureInfo.InvariantCulture) + "/" + group.Pairs.Length.ToString(System.Globalization.CultureInfo.InvariantCulture) + " clean)</a>");
        }

        sb.AppendLine("</div>");
    }

    private static void AppendComparisonGroup(System.Text.StringBuilder sb, ComparisonGroup group, string output) {
        sb.AppendLine("<div class=\"family\" id=\"comparison-family-" + EscapeHtml(Slugify(group.Name)) + "\">");
        sb.AppendLine("<div class=\"family-head\"><div><h2 class=\"family-title\">" + EscapeHtml(group.Name) + "</h2><p class=\"family-desc\">" + EscapeHtml(group.Description) + "</p></div><span class=\"family-count " + (group.IsClean ? "ok" : "warn") + "\">" + group.Pairs.Length.ToString(System.Globalization.CultureInfo.InvariantCulture) + " pairs / " + group.CleanPairs.ToString(System.Globalization.CultureInfo.InvariantCulture) + " clean / " + group.WarningCount.ToString(System.Globalization.CultureInfo.InvariantCulture) + " warnings</span></div>");
        foreach (var pair in group.Pairs) {
            AppendComparisonCard(sb, pair, output);
        }

        sb.AppendLine("</div>");
    }

    private static ComparisonAsset ReadComparisonAsset(string output, string name) {
        var svgFileName = Path.Combine(output, name + ".svg");
        var pngFileName = Path.Combine(output, name + ".png");
        return new ComparisonAsset(
            name,
            ReadSvgDimensions(svgFileName),
            ReadPngDimensions(pngFileName),
            ReadFileLength(svgFileName),
            ReadFileLength(pngFileName),
            ReadSvgHealth(svgFileName),
            ReadPngHealth(pngFileName),
            ReadHtmlHealth(Path.Combine(output, name + ".html")));
    }

    private static void WriteComparisonManifest(string output, ComparisonAsset[] pairs, int matchingPairs, BaselineSummary baseline) {
        var manifest = new {
            chartPairs = pairs.Length,
            dimensionMatches = matchingPairs,
            healthySvgs = pairs.Count(pair => pair.SvgHealth.IsHealthy),
            healthyPngs = pairs.Count(pair => pair.PngHealth.IsHealthy),
            healthyHtmls = pairs.Count(pair => pair.HtmlHealth.IsHealthy),
            warnings = pairs.Sum(pair => pair.Warnings.Length),
            baseline = new {
                present = baseline.IsPresent,
                chartMatches = baseline.ChartMatches,
                warnings = baseline.Warnings,
                clean = baseline.IsClean
            },
            healthThresholds = new {
                svgVisualNodes = MinimumHealthySvgVisualNodes,
                svgMinimumTextFontSize = MinimumReadableSvgTextFontSize,
                svgMinimumStrokeWidth = MinimumReadableSvgStrokeWidth,
                svgMinimumMarkerRadius = MinimumReadableSvgMarkerRadius,
                pngVisiblePixels = MinimumHealthyPngVisiblePixels,
                pngDistinctColors = MinimumHealthyPngDistinctColors,
                pngEdgeInkPixels = MaximumHealthyPngEdgeInkPixels,
                htmlRequiresDocumentShell = true,
                htmlRequiresViewport = true,
                htmlRequiresInlineSvg = true,
                htmlRequiresSurfaceGradient = true,
                htmlRequiresTextPolish = true,
                htmlRequiresVisibleOverflow = true,
                htmlRequiresPrintCss = true
            },
            comparisonModes = new[] { "side-by-side", "center-wipe", "preset-wipe" },
            charts = pairs.Select(pair => new {
                name = pair.Name,
                dimensionsMatch = pair.HasMatchingDimensions,
                warnings = pair.Warnings,
                svg = new {
                    width = pair.SvgDimensions.Width,
                    height = pair.SvgDimensions.Height,
                    bytes = pair.SvgBytes,
                    visualNodes = pair.SvgHealth.VisualNodes,
                    textNodes = pair.SvgHealth.TextNodes,
                    minimumTextFontSize = pair.SvgHealth.MinimumTextFontSize,
                    tinyTextNodes = pair.SvgHealth.TinyTextNodes,
                    strokedNodes = pair.SvgHealth.StrokedNodes,
                    minimumStrokeWidth = pair.SvgHealth.MinimumStrokeWidth,
                    tinyStrokeNodes = pair.SvgHealth.TinyStrokeNodes,
                    markerNodes = pair.SvgHealth.MarkerNodes,
                    minimumMarkerRadius = pair.SvgHealth.MinimumMarkerRadius,
                    tinyMarkerNodes = pair.SvgHealth.TinyMarkerNodes,
                    clippedTextNodes = pair.SvgHealth.ClippedTextNodes,
                    nearEdgeTextNodes = pair.SvgHealth.NearEdgeTextNodes,
                    healthy = pair.SvgHealth.IsHealthy
                },
                png = new {
                    width = pair.PngDimensions.Width,
                    height = pair.PngDimensions.Height,
                    scale = pair.PngScale,
                    bytes = pair.PngBytes,
                    visiblePixels = pair.PngHealth.VisiblePixels,
                    foregroundPixels = pair.PngHealth.ForegroundPixels,
                    contentBounds = new {
                        left = pair.PngHealth.ContentBounds.Left,
                        top = pair.PngHealth.ContentBounds.Top,
                        right = pair.PngHealth.ContentBounds.Right,
                        bottom = pair.PngHealth.ContentBounds.Bottom,
                        width = pair.PngHealth.ContentBounds.Width,
                        height = pair.PngHealth.ContentBounds.Height
                    },
                    distinctColors = pair.PngHealth.DistinctColors,
                    edgeInkPixels = pair.PngHealth.EdgeInkPixels,
                    edgeBandPixels = pair.PngHealth.EdgeBandPixels,
                    healthy = pair.PngHealth.IsHealthy
                },
                html = new {
                    bytes = pair.HtmlHealth.Bytes,
                    hasDocumentShell = pair.HtmlHealth.HasDocumentShell,
                    hasViewport = pair.HtmlHealth.HasViewport,
                    hasInlineSvg = pair.HtmlHealth.HasInlineSvg,
                    hasSurfaceGradient = pair.HtmlHealth.HasSurfaceGradient,
                    hasTextPolish = pair.HtmlHealth.HasTextPolish,
                    hasVisibleOverflow = pair.HtmlHealth.HasVisibleOverflow,
                    hasPrintCss = pair.HtmlHealth.HasPrintCss,
                    healthy = pair.HtmlHealth.IsHealthy
                }
            }).ToArray()
        };
        var options = new System.Text.Json.JsonSerializerOptions { WriteIndented = true };
        File.WriteAllText(Path.Combine(output, ComparisonManifestFileName), System.Text.Json.JsonSerializer.Serialize(manifest, options));
    }

    private static BaselineSummary ReadBaselineSummary(string output, ComparisonAsset[] pairs) {
        var baselineFile = FindVisualBaselineFile(output);
        if (baselineFile.Length == 0) return default;
        try {
            using var document = System.Text.Json.JsonDocument.Parse(File.ReadAllText(baselineFile));
            var baselineCharts = document.RootElement.GetProperty("charts").EnumerateArray().ToArray();
            var generated = pairs.ToDictionary(pair => pair.Name, StringComparer.OrdinalIgnoreCase);
            var expected = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var matches = 0;
            var warnings = 0;
            foreach (var baselineChart in baselineCharts) {
                var name = baselineChart.GetProperty("name").GetString() ?? string.Empty;
                if (!expected.Add(name) || !generated.TryGetValue(name, out var actual)) {
                    warnings++;
                    continue;
                }

                var width = baselineChart.GetProperty("width").GetInt32();
                var height = baselineChart.GetProperty("height").GetInt32();
                var svgBaseline = baselineChart.GetProperty("svg");
                var pngBaseline = baselineChart.GetProperty("png");
                var minVisualNodes = svgBaseline.GetProperty("minVisualNodes").GetInt32();
                var maxClippedTextNodes = ReadBaselineInt32(svgBaseline, "maxClippedTextNodes", int.MaxValue);
                var maxNearEdgeTextNodes = ReadBaselineInt32(svgBaseline, "maxNearEdgeTextNodes", int.MaxValue);
                var minVisiblePixels = pngBaseline.GetProperty("minVisiblePixels").GetInt64();
                var minDistinctColors = pngBaseline.GetProperty("minDistinctColors").GetInt32();
                var outputScale = ReadBaselineInt32(pngBaseline, "outputScale", actual.PngScale);
                var maxEdgeInkPixels = ReadBaselineInt64(pngBaseline, "maxEdgeInkPixels", long.MaxValue);
                if (actual.SvgDimensions.Width == width &&
                    actual.SvgDimensions.Height == height &&
                    actual.PngScale == outputScale &&
                    actual.PngDimensions.Width == width * outputScale &&
                    actual.PngDimensions.Height == height * outputScale &&
                    actual.SvgHealth.VisualNodes >= minVisualNodes &&
                    actual.SvgHealth.ClippedTextNodes <= maxClippedTextNodes &&
                    actual.SvgHealth.NearEdgeTextNodes <= maxNearEdgeTextNodes &&
                    actual.PngHealth.VisiblePixels >= minVisiblePixels &&
                    actual.PngHealth.DistinctColors >= minDistinctColors &&
                    actual.PngHealth.EdgeInkPixels <= maxEdgeInkPixels) {
                    matches++;
                } else {
                    warnings++;
                }
            }

            foreach (var pair in pairs) {
                if (!expected.Contains(pair.Name)) warnings++;
            }

            return new BaselineSummary(true, matches, warnings);
        } catch (IOException) {
        } catch (UnauthorizedAccessException) {
        } catch (System.Text.Json.JsonException) {
        } catch (InvalidOperationException) {
        } catch (KeyNotFoundException) {
        }

        return new BaselineSummary(true, 0, pairs.Length);
    }

    private static int ReadBaselineInt32(System.Text.Json.JsonElement element, string name, int fallback) {
        return element.TryGetProperty(name, out var value) &&
            value.ValueKind == System.Text.Json.JsonValueKind.Number &&
            value.TryGetInt32(out var number)
                ? number
                : fallback;
    }

    private static long ReadBaselineInt64(System.Text.Json.JsonElement element, string name, long fallback) {
        return element.TryGetProperty(name, out var value) &&
            value.ValueKind == System.Text.Json.JsonValueKind.Number &&
            value.TryGetInt64(out var number)
                ? number
                : fallback;
    }

    private static string FindVisualBaselineFile(string output) {
        var directory = new DirectoryInfo(Path.GetFullPath(output));
        while (directory != null) {
            var candidate = Path.Combine(directory.FullName, VisualBaselineFileName);
            if (File.Exists(candidate)) return candidate;
            directory = directory.Parent;
        }

        return string.Empty;
    }

    private static string FormatBaselinePill(BaselineSummary baseline) {
        if (!baseline.IsPresent) return "<span class=\"pill warn\">no baseline</span>";
        return "<span class=\"pill " + (baseline.IsClean ? "ok" : "warn") + "\">" + baseline.ChartMatches.ToString(System.Globalization.CultureInfo.InvariantCulture) + " baseline passes</span><span class=\"pill " + (baseline.Warnings == 0 ? "ok" : "warn") + "\">" + baseline.Warnings.ToString(System.Globalization.CultureInfo.InvariantCulture) + " baseline warnings</span>";
    }

    private static void AppendComparisonStyle(System.Text.StringBuilder sb) {
        sb.AppendLine("""
:root{color-scheme:dark;--bg:#0f172a;--panel:#111827;--frame:#020617;--line:#334155;--text:#e5e7eb;--muted:#94a3b8;--ok:#86efac;--warn:#fbbf24;--accent:#38bdf8}
*{box-sizing:border-box}body{margin:0;padding:24px;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,Segoe UI,Arial,sans-serif}
header{max-width:1500px;margin:0 auto 24px}h1{margin:0 0 6px;font-size:24px;line-height:1.15}p{margin:0;color:var(--muted)}.summary,.family-nav{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.pill,.family-nav a{border:1px solid var(--line);border-radius:999px;padding:6px 10px;color:#cbd5e1;font-size:12px;font-weight:700;text-decoration:none}.pill.ok,.family-nav a.ok{border-color:rgba(134,239,172,.45);color:var(--ok)}.pill.warn,.family-nav a.warn{border-color:rgba(251,191,36,.55);color:var(--warn)}a.pill:hover,.family-nav a:hover{border-color:rgba(56,189,248,.55);color:var(--accent)}main{display:grid;gap:34px;max-width:1500px;margin:0 auto}
.family{display:grid;gap:16px}.family-head{display:flex;align-items:end;justify-content:space-between;gap:16px;border-bottom:1px solid var(--line);padding-bottom:12px}.family-title{margin:0 0 5px;font-size:19px;line-height:1.15;color:#f8fafc}.family-desc{font-size:13px}.family-count{flex:0 0 auto;border:1px solid rgba(56,189,248,.42);border-radius:999px;color:var(--accent);font-size:12px;font-weight:800;padding:6px 10px}.family-count.ok{border-color:rgba(134,239,172,.45);color:var(--ok)}.family-count.warn{border-color:rgba(251,191,36,.55);color:var(--warn)}section{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:16px;scroll-margin-top:18px;overflow:hidden}section.mismatch{border-color:rgba(251,191,36,.6)}h2{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:0 0 14px;font-size:14px;color:#cbd5e1}.status{border:1px solid var(--line);border-radius:999px;padding:4px 8px;font-size:11px;font-weight:800}.status.ok{color:var(--ok);border-color:rgba(134,239,172,.45)}.status.warn{color:var(--warn);border-color:rgba(251,191,36,.55)}.pair{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;align-items:start}section.large .pair{grid-template-columns:1fr}.wipe-figure{grid-column:1/-1;order:-1}.wipe-figure .media{min-height:360px}section.large .wipe-figure .media{min-height:min(68vh,820px)}section.large figure:not(.wipe-figure) .media{min-height:min(62vh,720px)}
figure{margin:0;background:var(--frame);border:1px solid #1f2937;border-radius:8px;padding:10px;min-width:0}.caption{display:flex;justify-content:space-between;gap:12px;color:var(--muted);font-size:12px;margin-bottom:8px}.dims{font-variant-numeric:tabular-nums;color:#cbd5e1}.format{color:var(--accent);font-weight:800;text-decoration:none}.format:hover{text-decoration:underline}.wipe-frame{display:grid;gap:10px;justify-items:start}.wipe-frame>input{position:absolute;opacity:0;pointer-events:none}.wipe-controls{display:flex;flex-wrap:wrap;align-items:center;gap:6px;margin:0}.wipe-controls label{display:inline-flex;align-items:center;justify-content:center;min-height:30px;border:1px solid var(--line);border-radius:999px;color:#cbd5e1;cursor:pointer;font-size:11px;font-weight:800;line-height:1;max-width:100%;padding:5px 9px;white-space:nowrap}.wipe-frame>input:focus-visible~.wipe-controls{outline:2px solid var(--accent);outline-offset:3px}.wipe-frame>.wipe-25:checked~.wipe-controls label[for$="-25"],.wipe-frame>.wipe-50:checked~.wipe-controls label[for$="-50"],.wipe-frame>.wipe-75:checked~.wipe-controls label[for$="-75"]{background:rgba(56,189,248,.16);border-color:rgba(56,189,248,.7);color:#f8fafc}
.media{width:100%;min-height:140px;background-color:#020617;background-image:linear-gradient(45deg,#0b1120 25%,transparent 25%),linear-gradient(-45deg,#0b1120 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#0b1120 75%),linear-gradient(-45deg,transparent 75%,#0b1120 75%);background-size:24px 24px;background-position:0 0,0 12px,12px -12px,-12px 0;overflow:hidden}.media.wipe{position:relative;--wipe:50%}.wipe-frame>.wipe-25:checked~.media{--wipe:25%}.wipe-frame>.wipe-50:checked~.media{--wipe:50%}.wipe-frame>.wipe-75:checked~.media{--wipe:75%}.media.wipe img,.media.wipe object{position:absolute;inset:0}.media.wipe object{clip-path:inset(0 calc(100% - var(--wipe)) 0 0)}.media.wipe:before{content:"";position:absolute;z-index:3;top:0;bottom:0;left:var(--wipe);border-left:2px solid rgba(56,189,248,.9);box-shadow:0 0 0 1px rgba(2,6,23,.85)}.media.wipe:after{content:"SVG | PNG";position:absolute;z-index:4;left:var(--wipe);top:8px;transform:translateX(-50%);border:1px solid rgba(56,189,248,.4);border-radius:999px;background:rgba(2,6,23,.82);color:#e5e7eb;font-size:10px;font-weight:800;letter-spacing:.08em;padding:4px 8px}object,img{display:block;width:100%;height:100%;object-fit:contain;background:transparent}.code-samples{grid-column:1/-1;display:grid;gap:10px}.code-sample{border:1px solid #1f2937;border-radius:8px;background:#020617}.code-sample summary{cursor:pointer;color:var(--accent);font-size:12px;font-weight:850;padding:10px 12px}.code-sample pre{margin:0;max-height:520px;overflow:auto;border-top:1px solid #1f2937;padding:12px}.code-sample code{font-family:ui-monospace,SFMono-Regular,Consolas,Liberation Mono,monospace;font-size:12px;line-height:1.55;color:#dbeafe;white-space:pre}
@media(max-width:1200px){.pair{grid-template-columns:1fr}}@media(max-width:900px){body{padding:16px}}
""");
    }

    private static void AppendComparisonCard(System.Text.StringBuilder sb, ComparisonAsset pair, string output) {
        var name = pair.Name;
        var svg = pair.SvgDimensions;
        var png = pair.PngDimensions;
        var aspectWidth = svg.Width > 0 ? svg.Width : png.Width;
        var aspectHeight = svg.Height > 0 ? svg.Height : png.Height;
        if (aspectWidth <= 0 || aspectHeight <= 0) {
            aspectWidth = 16;
            aspectHeight = 9;
        }

        var ratioStyle = " style=\"aspect-ratio:" + aspectWidth.ToString(System.Globalization.CultureInfo.InvariantCulture) + "/" + aspectHeight.ToString(System.Globalization.CultureInfo.InvariantCulture) + ";max-width:" + aspectWidth.ToString(System.Globalization.CultureInfo.InvariantCulture) + "px;margin-inline:auto\"";
        var warnings = pair.Warnings;
        var statusClass = warnings.Length == 0 ? "ok" : "warn";
        var statusText = warnings.Length == 0 ? "Review clean" : string.Join(" / ", warnings);
        var svgInfo = FormatDimensions(svg) + " / " + FormatBytes(pair.SvgBytes) + " / " + pair.SvgHealth.VisualNodes.ToString(System.Globalization.CultureInfo.InvariantCulture) + " visual nodes / min text " + FormatSvgTextSize(pair.SvgHealth.MinimumTextFontSize) + " / min stroke " + FormatSvgStrokeWidth(pair.SvgHealth.MinimumStrokeWidth) + " / min marker " + FormatSvgMarkerRadius(pair.SvgHealth.MinimumMarkerRadius);
        var scaleLabel = pair.PngScale > 1 ? " @" + pair.PngScale.ToString(System.Globalization.CultureInfo.InvariantCulture) + "x" : string.Empty;
        var pngInfo = FormatDimensions(png) + scaleLabel + " / " + FormatBytes(pair.PngBytes) + " / " + pair.PngHealth.VisiblePixels.ToString(System.Globalization.CultureInfo.InvariantCulture) + " visible px / " + pair.PngHealth.ForegroundPixels.ToString(System.Globalization.CultureInfo.InvariantCulture) + " foreground px";
        var largeClass = aspectWidth >= 1200 || aspectHeight >= 900 ? " large" : string.Empty;
        sb.AppendLine("<section id=\"" + EscapeHtml(name) + "\" class=\"" + (pair.HasMatchingDimensions ? "match" : "mismatch") + largeClass + "\">");
        sb.AppendLine("<h2><span>" + EscapeHtml(name) + "</span><span class=\"status " + statusClass + "\">" + statusText + "</span></h2>");
        sb.AppendLine("<div class=\"pair\">");
        AppendComparisonWipeFigure(sb, name, svg, ratioStyle);
        AppendComparisonAssetFigure(sb, name, "SVG", "svg", "object", svgInfo, ratioStyle);
        AppendComparisonAssetFigure(sb, name, "PNG", "png", "img", pngInfo, ratioStyle);
        AppendCodeSamples(sb, output, name);
        sb.AppendLine("</div>");
        sb.AppendLine("</section>");
    }

    private static void AppendComparisonWipeFigure(System.Text.StringBuilder sb, string name, AssetDimensions svg, string ratioStyle) {
        var escapedName = EscapeHtml(name);
        var escapedWipeId = EscapeHtml(Slugify(name));
        sb.AppendLine("<figure class=\"wipe-figure\"><figcaption class=\"caption\"><span class=\"format\">WIPE</span><span class=\"dims\">" + EscapeHtml(FormatDimensions(svg)) + "</span></figcaption><div class=\"wipe-frame\" aria-label=\"" + escapedName + " wipe position\"><input class=\"wipe-25\" type=\"radio\" name=\"wipe-" + escapedWipeId + "\" id=\"wipe-" + escapedWipeId + "-25\"><input class=\"wipe-50\" type=\"radio\" name=\"wipe-" + escapedWipeId + "\" id=\"wipe-" + escapedWipeId + "-50\" checked><input class=\"wipe-75\" type=\"radio\" name=\"wipe-" + escapedWipeId + "\" id=\"wipe-" + escapedWipeId + "-75\"><div class=\"wipe-controls\"><label for=\"wipe-" + escapedWipeId + "-25\">SVG 25%</label><label for=\"wipe-" + escapedWipeId + "-50\">Split</label><label for=\"wipe-" + escapedWipeId + "-75\">SVG 75%</label></div><div class=\"media wipe\"" + ratioStyle + "><img src=\"" + escapedName + ".png\" alt=\"" + escapedName + " PNG wipe right\"><object data=\"" + escapedName + ".svg\" type=\"image/svg+xml\" aria-label=\"" + escapedName + " SVG wipe left\"></object></div></div></figure>");
    }

    private static void AppendComparisonAssetFigure(System.Text.StringBuilder sb, string name, string label, string extension, string mediaKind, string dimensions, string ratioStyle) {
        var escapedName = EscapeHtml(name);
        var escapedDimensions = EscapeHtml(dimensions);
        var href = escapedName + "." + extension;
        var media = string.Equals(mediaKind, "object", StringComparison.Ordinal)
            ? "<object data=\"" + href + "\" type=\"image/svg+xml\"></object>"
            : "<img src=\"" + href + "\" alt=\"" + escapedName + " " + label + "\">";
        sb.AppendLine("<figure><figcaption class=\"caption\"><a class=\"format\" href=\"" + href + "\">" + label + "</a><span class=\"dims\">" + escapedDimensions + "</span></figcaption><div class=\"media\"" + ratioStyle + ">" + media + "</div></figure>");
    }

    private static bool IsGalleryShellFile(string fileName) =>
        string.Equals(fileName, IndexFileName, StringComparison.OrdinalIgnoreCase) ||
        string.Equals(fileName, CatalogFileName, StringComparison.OrdinalIgnoreCase) ||
        string.Equals(fileName, QualityDashboardFileName, StringComparison.OrdinalIgnoreCase) ||
        string.Equals(fileName, ComparisonFileName, StringComparison.OrdinalIgnoreCase);

    private static bool IsConflictCopyFile(string file) {
        var baseName = Path.GetFileNameWithoutExtension(file);
        var canonicalBaseName = StripConflictCopySuffix(baseName);
        if (string.Equals(canonicalBaseName, baseName, StringComparison.Ordinal)) return false;
        var directory = Path.GetDirectoryName(file) ?? string.Empty;
        return File.Exists(Path.Combine(directory, canonicalBaseName + Path.GetExtension(file)));
    }

    private static string StripConflictCopySuffix(string baseName) {
        var separator = baseName.LastIndexOf(' ');
        if (separator < 1 || separator == baseName.Length - 1) return baseName;
        for (var i = separator + 1; i < baseName.Length; i++) {
            if (!char.IsDigit(baseName[i])) return baseName;
        }

        return baseName.Substring(0, separator);
    }

    private static AssetDimensions ReadSvgDimensions(string fileName) {
        try {
            var svg = File.ReadAllText(Path.GetFullPath(fileName));
            var width = ReadSvgNumericAttribute(svg, "width");
            var height = ReadSvgNumericAttribute(svg, "height");
            if (width > 0 && height > 0) return new AssetDimensions(width, height);
            var viewBox = ReadSvgAttribute(svg, "viewBox");
            if (!string.IsNullOrWhiteSpace(viewBox)) {
                var parts = viewBox.Split(new[] { ' ', ',' }, StringSplitOptions.RemoveEmptyEntries);
                if (parts.Length == 4 &&
                    double.TryParse(parts[2], System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var viewWidth) &&
                    double.TryParse(parts[3], System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var viewHeight)) {
                    return new AssetDimensions((int)Math.Round(viewWidth), (int)Math.Round(viewHeight));
                }
            }
        } catch (IOException) {
        } catch (UnauthorizedAccessException) {
        }

        return default;
    }

    private static AssetDimensions ReadPngDimensions(string fileName) {
        try {
            var fullPath = Path.GetFullPath(fileName);
            using var stream = File.OpenRead(fullPath);
            var header = new byte[24];
            if (stream.Read(header, 0, header.Length) != header.Length) return default;
            if (header[0] != 137 || header[1] != 80 || header[2] != 78 || header[3] != 71) return default;
            return new AssetDimensions(ReadBigEndianInt32(header, 16), ReadBigEndianInt32(header, 20));
        } catch (IOException) {
        } catch (UnauthorizedAccessException) {
        }

        return default;
    }

    private static string FormatDimensions(AssetDimensions dimensions) {
        return dimensions.Width > 0 && dimensions.Height > 0
            ? dimensions.Width.ToString(System.Globalization.CultureInfo.InvariantCulture) + "x" + dimensions.Height.ToString(System.Globalization.CultureInfo.InvariantCulture)
            : "unknown";
    }

    private static string FormatBytes(long bytes) {
        if (bytes >= 1024 * 1024) return (bytes / (1024d * 1024d)).ToString("0.#", System.Globalization.CultureInfo.InvariantCulture) + " MB";
        if (bytes >= 1024) return (bytes / 1024d).ToString("0.#", System.Globalization.CultureInfo.InvariantCulture) + " KB";
        return bytes.ToString(System.Globalization.CultureInfo.InvariantCulture) + " B";
    }

    private static string FormatSvgTextSize(double fontSize) =>
        fontSize > 0 ? fontSize.ToString("0.#", System.Globalization.CultureInfo.InvariantCulture) + "px" : "n/a";

    private static string FormatSvgStrokeWidth(double strokeWidth) =>
        strokeWidth > 0 ? strokeWidth.ToString("0.##", System.Globalization.CultureInfo.InvariantCulture) + "px" : "n/a";

    private static string FormatSvgMarkerRadius(double radius) =>
        radius > 0 ? radius.ToString("0.##", System.Globalization.CultureInfo.InvariantCulture) + "px" : "n/a";

    private static int ReadSvgNumericAttribute(string svg, string name) {
        var value = ReadSvgAttribute(svg, name);
        if (string.IsNullOrWhiteSpace(value)) return 0;
        var digits = new string(value.TakeWhile(ch => char.IsDigit(ch) || ch == '.').ToArray());
        return double.TryParse(digits, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var number)
            ? (int)Math.Round(number)
            : 0;
    }

    private static string ReadSvgAttribute(string svg, string name) {
        var marker = name + "=\"";
        var start = svg.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
        if (start < 0) return string.Empty;
        start += marker.Length;
        var end = svg.IndexOf('"', start);
        return end > start ? svg.Substring(start, end - start) : string.Empty;
    }

    private static int ReadBigEndianInt32(byte[] bytes, int offset) {
        return (bytes[offset] << 24) | (bytes[offset + 1] << 16) | (bytes[offset + 2] << 8) | bytes[offset + 3];
    }

    private static long ReadFileLength(string fileName) {
        try {
            return new FileInfo(fileName).Length;
        } catch (IOException) {
        } catch (UnauthorizedAccessException) {
        }

        return 0;
    }

    private static SvgHealth ReadSvgHealth(string fileName) {
        try {
            var svg = File.ReadAllText(Path.GetFullPath(fileName));
            var visualNodes =
                CountOccurrences(svg, "<path") +
                CountOccurrences(svg, "<rect") +
                CountOccurrences(svg, "<circle") +
                CountOccurrences(svg, "<line") +
                CountOccurrences(svg, "<polygon") +
                CountOccurrences(svg, "<polyline") +
                CountOccurrences(svg, "<text");
            var textNodes = CountOccurrences(svg, "<text");
            var textQuality = ReadSvgTextQuality(svg, ReadSvgDimensions(fileName));
            return new SvgHealth(visualNodes, textNodes, textQuality.MinimumFontSize, textQuality.TinyTextNodes, textQuality.StrokedNodes, textQuality.MinimumStrokeWidth, textQuality.TinyStrokeNodes, textQuality.MarkerNodes, textQuality.MinimumMarkerRadius, textQuality.TinyMarkerNodes, textQuality.ClippedTextNodes, textQuality.NearEdgeTextNodes);
        } catch (IOException) {
        } catch (UnauthorizedAccessException) {
        }

        return default;
    }

    private static PngHealth ReadPngHealth(string fileName) {
        try {
            var png = File.ReadAllBytes(Path.GetFullPath(fileName));
            var dimensions = ReadPngDimensions(fileName);
            if (dimensions.Width <= 0 || dimensions.Height <= 0) return default;
            var idat = new List<byte>();
            var offset = 8;
            while (offset + 8 <= png.Length) {
                var length = ReadBigEndianInt32(png, offset);
                if (length < 0 || offset + 12 + length > png.Length) return default;
                var type = System.Text.Encoding.ASCII.GetString(png, offset + 4, 4);
                if (type == "IDAT") {
                    for (var i = 0; i < length; i++) idat.Add(png[offset + 8 + i]);
                }

                offset += 12 + length;
            }

            if (idat.Count <= 6) return default;
            using var source = new MemoryStream(idat.ToArray(), 2, idat.Count - 6);
            using var deflate = new System.IO.Compression.DeflateStream(source, System.IO.Compression.CompressionMode.Decompress);
            using var inflated = new MemoryStream();
            deflate.CopyTo(inflated);
            var raw = inflated.ToArray();
            var stride = dimensions.Width * 4;
            if (raw.Length < dimensions.Height * (stride + 1)) return default;
            var previous = new byte[stride];
            var current = new byte[stride];
            var visiblePixels = 0L;
            var colors = new HashSet<int>();
            var edgeColors = new List<int>();
            var cornerColors = new Dictionary<int, int>();
            var edgeBand = PngEdgeBandSize(dimensions);
            var pixelColors = new int[dimensions.Width * dimensions.Height];
            var rawOffset = 0;
            for (var y = 0; y < dimensions.Height; y++) {
                var filter = raw[rawOffset++];
                if (rawOffset + stride > raw.Length || !UnfilterPngRow(raw, rawOffset, current, previous, stride, 4, filter)) return default;
                rawOffset += stride;
                for (var x = 0; x < stride; x += 4) {
                    var r = current[x];
                    var g = current[x + 1];
                    var b = current[x + 2];
                    var a = current[x + 3];
                    if (a > 0) visiblePixels++;
                    var key = PngColorKey(r, g, b, a);
                    pixelColors[y * dimensions.Width + x / 4] = key;
                    if (colors.Count < 4096) colors.Add(key);
                    TrackPngEdgeSamples(dimensions, x / 4, y, edgeBand, key, cornerColors, edgeColors);
                }

                var swap = previous;
                previous = current;
                current = swap;
            }

            var edgeBackground = DominantPngCornerColor(cornerColors);
            var visualBackground = DominantPngVisibleColor(pixelColors, edgeBackground);
            var foreground = CountPngForeground(pixelColors, dimensions, visualBackground, out var contentBounds);
            var edgeInkPixels = CountPngEdgeInk(edgeColors, edgeBackground);
            return new PngHealth(visiblePixels, foreground, contentBounds, colors.Count, edgeInkPixels, edgeColors.Count);
        } catch (IOException) {
        } catch (UnauthorizedAccessException) {
        } catch (InvalidDataException) {
        }

        return default;
    }

    private static bool UnfilterPngRow(byte[] raw, int rawOffset, byte[] output, byte[] previous, int stride, int bytesPerPixel, int filter) {
        switch (filter) {
            case 0:
                Buffer.BlockCopy(raw, rawOffset, output, 0, stride);
                return true;
            case 1:
                for (var i = 0; i < stride; i++) {
                    var left = i >= bytesPerPixel ? output[i - bytesPerPixel] : 0;
                    output[i] = unchecked((byte)(raw[rawOffset + i] + left));
                }

                return true;
            case 2:
                for (var i = 0; i < stride; i++) {
                    output[i] = unchecked((byte)(raw[rawOffset + i] + previous[i]));
                }

                return true;
            case 3:
                for (var i = 0; i < stride; i++) {
                    var left = i >= bytesPerPixel ? output[i - bytesPerPixel] : 0;
                    var up = previous[i];
                    output[i] = unchecked((byte)(raw[rawOffset + i] + ((left + up) >> 1)));
                }

                return true;
            case 4:
                for (var i = 0; i < stride; i++) {
                    var left = i >= bytesPerPixel ? output[i - bytesPerPixel] : 0;
                    var up = previous[i];
                    var upperLeft = i >= bytesPerPixel ? previous[i - bytesPerPixel] : 0;
                    output[i] = unchecked((byte)(raw[rawOffset + i] + PaethPredictor(left, up, upperLeft)));
                }

                return true;
            default:
                return false;
        }
    }

    private static int PaethPredictor(int left, int up, int upperLeft) {
        var estimate = left + up - upperLeft;
        var leftDistance = Math.Abs(estimate - left);
        var upDistance = Math.Abs(estimate - up);
        var upperLeftDistance = Math.Abs(estimate - upperLeft);
        if (leftDistance <= upDistance && leftDistance <= upperLeftDistance) return left;
        return upDistance <= upperLeftDistance ? up : upperLeft;
    }

    private static int CountOccurrences(string value, string pattern) {
        var count = 0;
        var index = 0;
        while ((index = value.IndexOf(pattern, index, StringComparison.OrdinalIgnoreCase)) >= 0) {
            count++;
            index += pattern.Length;
        }

        return count;
    }

    private static string EscapeHtml(string value) => System.Net.WebUtility.HtmlEncode(value);
}
