using ChartForgeX.Topology;

internal static partial class TopologyVisualExamples {
    private static TopologyChart BuildImpactDependencyOverview() {
        return TopologyChart.Create()
            .WithId("visual-impact-dependency-overview")
            .WithTitle("Impact Dependency Overview")
            .WithSubtitle("Reusable blast-radius map: dependencies, owners, consumers, controls, and risks around a selected platform.")
            .WithViewport(1120, 600, 28)
            .WithTheme(TopologyTheme.Light())
            .WithLegend(TopologyLegend.Create("Impact Legend")
                .AddNodeKind("Platform", TopologyNodeKind.Application, "#2563EB", "APP")
                .AddNodeKind("Dependency", TopologyNodeKind.Service, "#16A34A", "SVC")
                .AddNodeKind("Owner", TopologyNodeKind.Team, "#F97316", "OWN")
                .AddNodeKind("Finding", TopologyNodeKind.Process, "#EF4444", "!")
                .AddEdgeKind("Consumes", TopologyEdgeKind.Dependency, "#2563EB", TopologyEdgeLineStyle.Solid)
                .AddEdgeKind("Owns", TopologyEdgeKind.Ownership, "#F97316", TopologyEdgeLineStyle.Solid)
                .AddEdgeKind("Affected", TopologyEdgeKind.DataFlow, "#8B5CF6", TopologyEdgeLineStyle.Dashed)
                .AddEdgeKind("Risk", TopologyEdgeKind.Dependency, "#EF4444", TopologyEdgeLineStyle.Dotted))
            .AddNode("platform", "Client Portal API\nSelected Platform", 470, 228, TopologyNodeKind.Application, TopologyHealthStatus.Warning, subtitle: "99.91% availability\n4 linked risks", width: 214, height: 98, symbol: "APP", iconId: "chartforgex-app-service:application", color: "#2563EB")
            .AddNode("identity", "Identity Service\nOIDC + groups", 126, 104, TopologyNodeKind.Service, TopologyHealthStatus.Healthy, subtitle: "verified dependency\np95 62 ms", width: 202, height: 90, symbol: "ID", iconId: "chartforgex-identity-directory:identity", color: "#16A34A")
            .AddNode("database", "Customer DB\nRead/write store", 130, 366, TopologyNodeKind.Database, TopologyHealthStatus.Warning, subtitle: "primary replica\nlag 8m", width: 202, height: 90, symbol: "DB", iconId: "chartforgex-data-ownership-intelligence:database", color: "#16A34A")
            .AddNode("queue", "Export Queue\nAsync workload", 470, 82, TopologyNodeKind.Queue, TopologyHealthStatus.Healthy, subtitle: "depth 124\nhealthy", width: 198, height: 88, symbol: "Q", iconId: "chartforgex-app-service:queue", color: "#0891B2")
            .AddNode("owner", "Platform Team\nBusiness Owner", 790, 112, TopologyNodeKind.Team, TopologyHealthStatus.Healthy, subtitle: "primary owner\non-call active", width: 214, height: 90, symbol: "OWN", iconId: "chartforgex-people-org-workflow:team", color: "#F97316")
            .AddNode("consumer", "Executive Export\nDownstream Consumer", 790, 338, TopologyNodeKind.Process, TopologyHealthStatus.Healthy, subtitle: "uses API + queue\nlast run 06:42", width: 224, height: 94, symbol: "EXP", iconId: "chartforgex-app-service:workflow", color: "#8B5CF6")
            .AddNode("finding", "Risk Bundle (4)\n2 High + 2 Medium", 470, 454, TopologyNodeKind.Process, TopologyHealthStatus.Critical, subtitle: "token scope drift\nstale queue reader", width: 214, height: 92, symbol: "!", iconId: "chartforgex-security-risk-certificates:finding", color: "#EF4444")
            .AddEdge("identity-platform", "identity", "platform", "authenticates", TopologyEdgeKind.Dependency, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "OIDC")
            .AddEdge("database-platform", "database", "platform", "serves data", TopologyEdgeKind.Dependency, TopologyHealthStatus.Warning, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "lag 8m")
            .AddEdge("platform-queue", "platform", "queue", "publishes", TopologyEdgeKind.DataFlow, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "exports")
            .AddEdge("owner-platform", "owner", "platform", "owns", TopologyEdgeKind.Ownership, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "primary")
            .AddEdge("platform-consumer", "platform", "consumer", "feeds", TopologyEdgeKind.DataFlow, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "scheduled")
            .AddEdge("platform-finding", "platform", "finding", "has risk", TopologyEdgeKind.Dependency, TopologyHealthStatus.Critical, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "4 signals")
            .AddEdge("database-finding", "database", "finding", "contributes", TopologyEdgeKind.Dependency, TopologyHealthStatus.Warning, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "replica lag")
            .WithEdgePorts("identity-platform", TopologyEdgePort.Right, TopologyEdgePort.Left)
            .WithEdgePorts("database-platform", TopologyEdgePort.Right, TopologyEdgePort.Left)
            .WithEdgePorts("platform-queue", TopologyEdgePort.Top, TopologyEdgePort.Bottom)
            .WithEdgePorts("owner-platform", TopologyEdgePort.Left, TopologyEdgePort.Right)
            .WithEdgePorts("platform-consumer", TopologyEdgePort.Right, TopologyEdgePort.Left)
            .WithEdgePorts("platform-finding", TopologyEdgePort.Bottom, TopologyEdgePort.Top)
            .WithEdgeRouteLane("identity-platform", -28)
            .WithEdgeRouteLane("database-platform", 28)
            .WithEdgeRouteLane("owner-platform", -22)
            .WithEdgeRouteLane("platform-consumer", 24)
            .WithEdgeLabelOffset("identity-platform", -22, 12)
            .WithEdgeLabelOffset("database-platform", -28, -8)
            .WithEdgeLabelOffset("platform-queue", 72, 4)
            .WithEdgeLabelOffset("owner-platform", 20, 12)
            .WithEdgeLabelOffset("platform-consumer", 10, -18)
            .WithEdgeLabelOffset("platform-finding", -72, 0)
            .WithEdgeLabelOffset("database-finding", -42, 28)
            .WithEdgeLineStyle("platform-consumer", TopologyEdgeLineStyle.Dashed)
            .WithEdgeLineStyle("platform-finding", TopologyEdgeLineStyle.Dotted)
            .WithEdgeLineStyle("database-finding", TopologyEdgeLineStyle.Dotted)
            .WithEdgeColor("identity-platform", "#2563EB")
            .WithEdgeColor("database-platform", "#2563EB")
            .WithEdgeColor("platform-queue", "#8B5CF6")
            .WithEdgeColor("owner-platform", "#F97316")
            .WithEdgeColor("platform-consumer", "#8B5CF6")
            .WithEdgeColor("platform-finding", "#EF4444")
            .WithEdgeColor("database-finding", "#EF4444");
    }

    private static TopologyChart BuildOwnershipEvidenceBundle() {
        return TopologyChart.Create()
            .WithId("visual-ownership-evidence-bundle")
            .WithTitle("Ownership Evidence Bundle")
            .WithSubtitle("Selected asset evidence map with owners, certificate, DNS, IP, finding, and export package relationships.")
            .WithViewport(1120, 600, 28)
            .WithTheme(TopologyTheme.Light())
            .WithLegend(TopologyLegend.Create("Evidence Legend")
                .AddNodeKind("Asset", TopologyNodeKind.Namespace, "#16A34A", "A")
                .AddNodeKind("Evidence", TopologyNodeKind.Storage, "#2563EB", "EV")
                .AddNodeKind("Owner", TopologyNodeKind.Team, "#F97316", "OWN")
                .AddNodeKind("Finding", TopologyNodeKind.Process, "#EF4444", "!")
                .AddEdgeKind("Verified Evidence", TopologyEdgeKind.Mapping, "#16A34A", TopologyEdgeLineStyle.Solid)
                .AddEdgeKind("Observed Evidence", TopologyEdgeKind.Link, "#2563EB", TopologyEdgeLineStyle.Dashed)
                .AddEdgeKind("Ownership", TopologyEdgeKind.Ownership, "#F97316", TopologyEdgeLineStyle.Solid)
                .AddEdgeKind("Risk", TopologyEdgeKind.Dependency, "#EF4444", TopologyEdgeLineStyle.Dotted))
            .AddNode("asset", "api.contoso.example\nSelected Asset", 468, 230, TopologyNodeKind.Namespace, TopologyHealthStatus.Healthy, subtitle: "confidence 94%\n9 evidence records", width: 220, height: 98, symbol: "A", iconId: "chartforgex-identity-directory:domain", color: "#16A34A")
            .AddNode("certificate", "Certificate Chain\nLet's Encrypt R3", 134, 92, TopologyNodeKind.Certificate, TopologyHealthStatus.Healthy, subtitle: "valid 62 days\nSAN match", width: 212, height: 90, symbol: "TLS", iconId: "chartforgex-identity-directory:certificate", color: "#2563EB")
            .AddNode("dns", "DNS Bundle\nA, AAAA, CNAME", 124, 238, TopologyNodeKind.Database, TopologyHealthStatus.Healthy, subtitle: "4 records\nobserved", width: 206, height: 88, symbol: "DNS", iconId: "chartforgex-data-ownership-intelligence:records", color: "#0891B2")
            .AddNode("ip", "203.0.113.42\nEdge Address", 126, 386, TopologyNodeKind.Endpoint, TopologyHealthStatus.Warning, subtitle: "ASN 64512\nwatchlisted", width: 206, height: 88, symbol: "IP", iconId: "chartforgex-network-infrastructure:ip-address", color: "#0891B2")
            .AddNode("owner", "Web Platform Team\nAccountable Owner", 790, 92, TopologyNodeKind.Team, TopologyHealthStatus.Healthy, subtitle: "RACI: owner\npager active", width: 230, height: 92, symbol: "OWN", iconId: "chartforgex-people-org-workflow:team", color: "#F97316")
            .AddNode("finding", "Findings Bundle\n1 Critical + 3 High", 792, 254, TopologyNodeKind.Process, TopologyHealthStatus.Critical, subtitle: "TLS policy drift\nowner confirmed", width: 228, height: 92, symbol: "!", iconId: "chartforgex-security-risk-certificates:finding", color: "#EF4444")
            .AddNode("export", "Evidence Package\nClient Export", 790, 418, TopologyNodeKind.Storage, TopologyHealthStatus.Healthy, subtitle: "PDF + JSON\nredacted", width: 230, height: 92, symbol: "EV", iconId: "chartforgex-data-ownership-intelligence:evidence", color: "#2563EB")
            .AddEdge("cert-asset", "certificate", "asset", "validates", TopologyEdgeKind.CertificateChain, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "SAN")
            .AddEdge("dns-asset", "dns", "asset", "resolves", TopologyEdgeKind.Mapping, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "A/CNAME")
            .AddEdge("asset-ip", "asset", "ip", "observed at", TopologyEdgeKind.Link, TopologyHealthStatus.Warning, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "HTTP probe")
            .AddEdge("owner-asset", "owner", "asset", "owns", TopologyEdgeKind.Ownership, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "verified")
            .AddEdge("asset-finding", "asset", "finding", "has risk", TopologyEdgeKind.Dependency, TopologyHealthStatus.Critical, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "4 findings")
            .AddEdge("finding-export", "finding", "export", "included in", TopologyEdgeKind.DataFlow, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "evidence")
            .AddEdge("cert-export", "certificate", "export", "attached", TopologyEdgeKind.Link, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.Orthogonal, "PEM")
            .WithEdgePorts("cert-asset", TopologyEdgePort.Right, TopologyEdgePort.Left)
            .WithEdgePorts("dns-asset", TopologyEdgePort.Right, TopologyEdgePort.Left)
            .WithEdgePorts("asset-ip", TopologyEdgePort.Left, TopologyEdgePort.Right)
            .WithEdgePorts("owner-asset", TopologyEdgePort.Left, TopologyEdgePort.Right)
            .WithEdgePorts("asset-finding", TopologyEdgePort.Right, TopologyEdgePort.Left)
            .WithEdgePorts("finding-export", TopologyEdgePort.Bottom, TopologyEdgePort.Top)
            .WithEdgeRouteLane("cert-asset", -26)
            .WithEdgeRouteLane("dns-asset", 22)
            .WithEdgeRouteLane("asset-ip", -30)
            .WithEdgeRouteLane("owner-asset", -24)
            .WithEdgeLabelOffset("cert-asset", 12, -8)
            .WithEdgeLabelOffset("dns-asset", -20, 0)
            .WithEdgeLabelOffset("asset-ip", -22, 28)
            .WithEdgeLabelOffset("owner-asset", 8, 18)
            .WithEdgeLabelOffset("asset-finding", -10, 4)
            .WithEdgeLabelOffset("finding-export", 32, 0)
            .WithEdgeLabelOffset("cert-export", -70, 4)
            .WithEdgeLineStyle("asset-ip", TopologyEdgeLineStyle.Dashed)
            .WithEdgeLineStyle("asset-finding", TopologyEdgeLineStyle.Dotted)
            .WithEdgeLineStyle("cert-export", TopologyEdgeLineStyle.Dashed)
            .WithEdgeColor("cert-asset", "#16A34A")
            .WithEdgeColor("dns-asset", "#16A34A")
            .WithEdgeColor("asset-ip", "#2563EB")
            .WithEdgeColor("owner-asset", "#F97316")
            .WithEdgeColor("asset-finding", "#EF4444")
            .WithEdgeColor("finding-export", "#2563EB")
            .WithEdgeColor("cert-export", "#2563EB");
    }
}
