using ChartForgeX.Topology;

internal static partial class TopologyVisualExamples {
    private static TopologyChart BuildEntityRelationshipOverview() {
        return TopologyChart.Create()
            .WithId("visual-entity-relationship-overview")
            .WithTitle("Entity Relationship Overview")
            .WithSubtitle("Domain, certificate, DNS, ownership, hosting, and finding evidence in one reusable topology model.")
            .WithViewport(1180, 620, 28)
            .WithTheme(TopologyTheme.Light())
            .WithLegend(TopologyLegend.Create("Relationship Legend")
                .AddNodeKind("Domain", TopologyNodeKind.Namespace, "#16A34A", "D", iconId: "chartforgex-identity-directory:domain")
                .AddNodeKind("Certificate", TopologyNodeKind.Certificate, "#2563EB", "TLS", iconId: "chartforgex-identity-directory:certificate")
                .AddNodeKind("DNS Records", TopologyNodeKind.Database, "#8B5CF6", "DNS", iconId: "chartforgex-data-ownership-intelligence:records")
                .AddNodeKind("MX Records", TopologyNodeKind.Queue, "#8B5CF6", "MX", iconId: "chartforgex-identity-directory:mail")
                .AddNodeKind("Owner", TopologyNodeKind.Team, "#F97316", "ORG", iconId: "chartforgex-people-org-workflow:organization")
                .AddNodeKind("Finding", TopologyNodeKind.Process, "#EF4444", "!", iconId: "chartforgex-security-risk-certificates:finding")
                .AddEdgeKind("Certificate Chain", TopologyEdgeKind.CertificateChain, "#2563EB", TopologyEdgeLineStyle.Solid)
                .AddEdgeKind("Verified Link", TopologyEdgeKind.Mapping, "#16A34A", TopologyEdgeLineStyle.Solid)
                .AddEdgeKind("Observed Link", TopologyEdgeKind.Link, "#2563EB", TopologyEdgeLineStyle.Dashed)
                .AddEdgeKind("Ownership", TopologyEdgeKind.Ownership, "#F97316", TopologyEdgeLineStyle.Solid)
                .AddEdgeKind("Inferred Link", TopologyEdgeKind.Dependency, "#64748B", TopologyEdgeLineStyle.Dotted)
                .AddEdgeKind("Risk Link", TopologyEdgeKind.Dependency, "#EF4444", TopologyEdgeLineStyle.Dotted))
            .AddNode("domain", "ad.evotec.xyz\nPrimary Domain", 494, 246, TopologyNodeKind.Namespace, TopologyHealthStatus.Healthy, subtitle: "Confidence 92%\n24 linked records", width: 190, height: 94, symbol: "D", href: "/entities/ad.evotec.xyz", tooltip: "Selected primary entity", iconId: "chartforgex-identity-directory:domain", color: "#16A34A")
            .AddNode("certificate", "CN: ad.evotec.xyz\nLet's Encrypt R3", 454, 92, TopologyNodeKind.Certificate, TopologyHealthStatus.Healthy, subtitle: "Valid\n62 days left", width: 220, height: 92, symbol: "TLS", href: "/certificates/ad.evotec.xyz", iconId: "chartforgex-identity-directory:certificate", color: "#2563EB")
            .AddNode("dns", "DNS Records (18)\nA, AAAA, TXT, CNAME", 112, 108, TopologyNodeKind.Database, TopologyHealthStatus.Healthy, subtitle: "authoritative\n4 sources", width: 214, height: 92, symbol: "DNS", href: "/dns/ad.evotec.xyz", iconId: "chartforgex-data-ownership-intelligence:records", color: "#8B5CF6")
            .AddNode("ip1", "192.168.241.4\nHetzner Online", 98, 300, TopologyNodeKind.Endpoint, TopologyHealthStatus.Healthy, subtitle: "A record\nObserved", width: 204, height: 88, symbol: "IP", href: "/ip/192.168.241.4", iconId: "chartforgex-network-infrastructure:ip-address", color: "#0891B2")
            .AddNode("ip2", "192.168.241.5\nHetzner Online", 392, 408, TopologyNodeKind.Endpoint, TopologyHealthStatus.Healthy, subtitle: "AAAA peer\nObserved", width: 204, height: 88, symbol: "IP", href: "/ip/192.168.241.5", iconId: "chartforgex-network-infrastructure:ip-address", color: "#0891B2")
            .AddNode("mx", "MX Records (2)\nmx1.evotec.xyz", 806, 110, TopologyNodeKind.Queue, TopologyHealthStatus.Warning, subtitle: "priority 10\nTTL 300", width: 204, height: 90, symbol: "MX", href: "/mx/ad.evotec.xyz", iconId: "chartforgex-identity-directory:mail", color: "#8B5CF6")
            .AddNode("owner", "Evotec Technologies Ltd.\nOrganization", 798, 284, TopologyNodeKind.Team, TopologyHealthStatus.Healthy, subtitle: "Registrar match\nKATOWICE 2", width: 232, height: 92, symbol: "ORG", href: "/owners/evotec", iconId: "chartforgex-people-org-workflow:organization", color: "#F97316")
            .AddNode("finding", "Findings (7)\n3 Critical + 4 High", 828, 454, TopologyNodeKind.Process, TopologyHealthStatus.Critical, subtitle: "TLSv1.0 observed\nnew evidence", width: 220, height: 92, symbol: "!", href: "/findings/ad.evotec.xyz", iconId: "chartforgex-security-risk-certificates:finding", color: "#EF4444")
            .AddNode("asn", "AS24940\nHosting Provider", 102, 462, TopologyNodeKind.Network, TopologyHealthStatus.Healthy, subtitle: "Hetzner Online GmbH\nBGP/ASN", width: 210, height: 88, symbol: "ASN", href: "/asn/24940", iconId: "chartforgex-network-infrastructure:asn", color: "#0891B2")
            .AddEdge("cert-domain", "certificate", "domain", "validates", TopologyEdgeKind.CertificateChain, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "SAN match", href: "/relations/cert-domain", tertiaryLabel: "verified")
            .AddEdge("dns-domain", "dns", "domain", "authoritative", TopologyEdgeKind.Mapping, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "DNS")
            .AddEdge("domain-mx", "domain", "mx", "routes mail", TopologyEdgeKind.Link, TopologyHealthStatus.Warning, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "MX records")
            .AddEdge("domain-owner", "domain", "owner", "owned by", TopologyEdgeKind.Ownership, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "WHOIS match")
            .AddEdge("domain-ip1", "domain", "ip1", "resolves to", TopologyEdgeKind.Mapping, TopologyHealthStatus.Healthy, TopologyDirection.Bidirectional, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "A record")
            .AddEdge("domain-ip2", "domain", "ip2", "resolves to", TopologyEdgeKind.Mapping, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "AAAA record")
            .AddEdge("ip1-asn", "ip1", "asn", "announced by", TopologyEdgeKind.Dependency, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "BGP")
            .AddEdge("domain-finding", "domain", "finding", "has risk", TopologyEdgeKind.Dependency, TopologyHealthStatus.Critical, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "3 sources", tertiaryLabel: "critical")
            .AddEdge("ip2-finding", "ip2", "finding", "observed by", TopologyEdgeKind.Link, TopologyHealthStatus.Warning, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "probe")
            .WithEdgePorts("cert-domain", TopologyEdgePort.Bottom, TopologyEdgePort.Top)
            .WithEdgePorts("domain-owner", TopologyEdgePort.Right, TopologyEdgePort.Left)
            .WithEdgePorts("domain-mx", TopologyEdgePort.Right, TopologyEdgePort.Left)
            .WithEdgePorts("domain-finding", TopologyEdgePort.Bottom, TopologyEdgePort.Left)
            .WithEdgeRouteLane("domain-finding", 22)
            .WithEdgeLineStyle("cert-domain", TopologyEdgeLineStyle.Solid)
            .WithEdgeLineStyle("dns-domain", TopologyEdgeLineStyle.Dashed)
            .WithEdgeLineStyle("domain-ip1", TopologyEdgeLineStyle.Dashed)
            .WithEdgeLineStyle("domain-ip2", TopologyEdgeLineStyle.Dotted)
            .WithEdgeLineStyle("domain-finding", TopologyEdgeLineStyle.Dotted)
            .WithEdgeLineStyle("ip2-finding", TopologyEdgeLineStyle.Dotted)
            .WithEdgeColor("cert-domain", "#2563EB")
            .WithEdgeColor("dns-domain", "#16A34A")
            .WithEdgeColor("domain-ip1", "#16A34A")
            .WithEdgeColor("domain-ip2", "#16A34A")
            .WithEdgeColor("ip1-asn", "#64748B")
            .WithEdgeColor("domain-mx", "#2563EB")
            .WithEdgeColor("domain-owner", "#F97316")
            .WithEdgeColor("domain-finding", "#EF4444")
            .WithEdgeColor("ip2-finding", "#2563EB")
            .WithEdgesOfKind(TopologyEdgeKind.Dependency, emphasis: TopologyEdgeEmphasis.Strong)
            .WithEdgesOfKind(TopologyEdgeKind.Link, emphasis: TopologyEdgeEmphasis.Subtle);
    }

    private static TopologyChart BuildMiniCorrelationMap() {
        return TopologyChart.Create()
            .WithId("visual-mini-correlation-map")
            .WithTitle("Mini Correlation Map")
            .WithSubtitle("Small dashboard-card relationship map for selected assets.")
            .WithViewport(920, 420, 24)
            .WithTheme(TopologyTheme.Light())
            .WithLegend(TopologyLegend.Create(null)
                .AddEdgeKind("Verified", TopologyEdgeKind.Mapping, "#16A34A", TopologyEdgeLineStyle.Solid)
                .AddEdgeKind("Observed", TopologyEdgeKind.Link, "#2563EB", TopologyEdgeLineStyle.Dashed)
                .AddEdgeKind("Inferred", TopologyEdgeKind.Dependency, "#94A3B8", TopologyEdgeLineStyle.Dotted))
            .AddNode("dns", "DNS: ad.evotec.xyz\n10.1.4.10", 72, 116, TopologyNodeKind.Network, TopologyHealthStatus.Healthy, subtitle: "internal", width: 178, height: 74, symbol: "DNS", color: "#0891B2")
            .AddNode("ip", "IP: 192.168.2.146\nInternal", 72, 224, TopologyNodeKind.Endpoint, TopologyHealthStatus.Healthy, subtitle: "observed", width: 178, height: 74, symbol: "IP", color: "#0891B2")
            .AddNode("domain", "ad.evotec.xyz\nCertificate", 372, 170, TopologyNodeKind.Namespace, TopologyHealthStatus.Healthy, subtitle: "selected record", width: 186, height: 82, symbol: "D", color: "#2563EB")
            .AddNode("server", "evotec-web-01\n192.168.2.15", 668, 92, TopologyNodeKind.Server, TopologyHealthStatus.Healthy, subtitle: "hosting", width: 176, height: 74, symbol: "SRV", color: "#2563EB")
            .AddNode("finding", "Finding (7)\n3 Critical + 4 High", 658, 232, TopologyNodeKind.Process, TopologyHealthStatus.Critical, subtitle: "risk evidence", width: 196, height: 80, symbol: "!", color: "#EF4444")
            .AddEdge("dns-domain", "dns", "domain", "verified", TopologyEdgeKind.Mapping, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "DNS")
            .AddEdge("ip-domain", "ip", "domain", "observed", TopologyEdgeKind.Link, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "IP")
            .AddEdge("domain-server", "domain", "server", "inferred", TopologyEdgeKind.Dependency, TopologyHealthStatus.Unknown, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "host")
            .AddEdge("finding-domain", "domain", "finding", "selected", TopologyEdgeKind.Link, TopologyHealthStatus.Critical, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "risk")
            .WithEdgeLineStyle("ip-domain", TopologyEdgeLineStyle.Dashed)
            .WithEdgeLineStyle("domain-server", TopologyEdgeLineStyle.Dotted)
            .WithEdgeLineStyle("finding-domain", TopologyEdgeLineStyle.Dashed)
            .WithEdgeColor("dns-domain", "#16A34A")
            .WithEdgeColor("ip-domain", "#2563EB")
            .WithEdgeColor("domain-server", "#94A3B8")
            .WithEdgeColor("finding-domain", "#EF4444");
    }

    private static TopologyChart BuildEvidenceTimelineRelationship() {
        return TopologyChart.Create()
            .WithId("visual-evidence-timeline-relationship")
            .WithTitle("Evidence Timeline Relationship")
            .WithSubtitle("Timeline-shaped evidence stream connected to one reusable entity card.")
            .WithViewport(980, 470, 24)
            .WithTheme(TopologyTheme.Light())
            .WithLegend(TopologyLegend.Create("Timeline Legend")
                .AddEdgeKind("Observed Event", TopologyEdgeKind.Link, "#2563EB", TopologyEdgeLineStyle.Dashed)
                .AddEdgeKind("Confirmed Event", TopologyEdgeKind.Mapping, "#16A34A", TopologyEdgeLineStyle.Solid)
                .AddEdgeKind("Risk Event", TopologyEdgeKind.Dependency, "#EF4444", TopologyEdgeLineStyle.Dotted))
            .AddNode("event-cert", "06:59:22\nCertificate observed", 82, 96, TopologyNodeKind.Certificate, TopologyHealthStatus.Healthy, subtitle: "Let's Encrypt R3\nValid", width: 220, height: 80, symbol: "TLS", color: "#2563EB")
            .AddNode("event-ip", "06:58:41\nIP health change", 82, 184, TopologyNodeKind.Endpoint, TopologyHealthStatus.Healthy, subtitle: "192.168.241.4\nStatus: Up", width: 220, height: 80, symbol: "IP", color: "#16A34A")
            .AddNode("event-mx", "06:57:10\nMX record linked", 82, 272, TopologyNodeKind.Queue, TopologyHealthStatus.Warning, subtitle: "mx1.evotec.xyz\nTTL 300", width: 220, height: 80, symbol: "MX", color: "#8B5CF6")
            .AddNode("event-finding", "06:54:02\nNew finding detected", 82, 360, TopologyNodeKind.Process, TopologyHealthStatus.Critical, subtitle: "TLSv1.0 enabled\nEvidence bundle", width: 220, height: 80, symbol: "!", color: "#EF4444")
            .AddNode("entity", "ad.evotec.xyz\nSelected Entity", 610, 208, TopologyNodeKind.Namespace, TopologyHealthStatus.Warning, subtitle: "Confidence 90%\n7 unresolved findings", width: 232, height: 98, symbol: "D", color: "#F97316")
            .AddEdge("cert-entity", "event-cert", "entity", "cert", TopologyEdgeKind.Mapping, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "confirmed")
            .AddEdge("ip-entity", "event-ip", "entity", "ip", TopologyEdgeKind.Link, TopologyHealthStatus.Healthy, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "observed")
            .AddEdge("mx-entity", "event-mx", "entity", "mx", TopologyEdgeKind.Link, TopologyHealthStatus.Warning, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "observed")
            .AddEdge("finding-entity", "event-finding", "entity", "finding", TopologyEdgeKind.Dependency, TopologyHealthStatus.Critical, TopologyDirection.Forward, TopologyEdgeRouting.ObstacleAvoidingOrthogonal, "risk")
            .WithEdgeLineStyle("ip-entity", TopologyEdgeLineStyle.Dashed)
            .WithEdgeLineStyle("mx-entity", TopologyEdgeLineStyle.Dashed)
            .WithEdgeLineStyle("finding-entity", TopologyEdgeLineStyle.Dotted)
            .WithEdgeColor("cert-entity", "#16A34A")
            .WithEdgeColor("ip-entity", "#2563EB")
            .WithEdgeColor("mx-entity", "#8B5CF6")
            .WithEdgeColor("finding-entity", "#EF4444");
    }
}
